### ISSUE TITLE
Help: Camera not found after Synology NAS "soft" reset

### ISSUE THREAD

**Issue by NeverEatYellowSwissSnow** [djdd87/SynoAI#101]
Please raise an issue and when you do provide the logs, the screenshot of the camera config dialog showing the name and your config.

_Originally posted by @djdd87 in https://github.com/djdd87/SynoAI/discussions/100#discussioncomment-2120506_

EDIT: lol, wtf, downloaded latest docker image again and now the error is not showing up anymore. But here are still some strange log entries. Are they normal?
[djdd87-synoai_01.csv](https://github.com/djdd87/SynoAI/files/8010612/djdd87-synoai_01.csv)

**Comment by NeverEatYellowSwissSnow** [comment]
Closed the issue. Maybe you could still give me an answer about the remainings log warnings.
Thanks!

**Comment by djdd87** [comment]
Those aren't anything to worry about.
