### ISSUE TITLE
API endpoint to enable/disable cams

### ISSUE THREAD

**Issue by Sungray** [djdd87/SynoAI#105]
Hey, thank you for this very useful tool!

Would it be possible to add an endpoint to enable/disable cameras inside SynoAI?

The point would be to include SynoAPI into my alarm system. When the alarm is enabled, I want to enable the SynoAI. It would be much easier than working with the Syno API SYNO.SurveillanceStation.ActionRule.

Thanks!

**Comment by djdd87** [comment]
Should be doable at some point.

**Comment by djdd87** [comment]
Can now be done by POSTing to the respective camera's end point:

https://github.com/djdd87/SynoAI#camera-api

```json
{
  "Enabled": "false"
}
```
