### ISSUE TITLE
Any testing with Surveillance Station 9.0 Beta? Also, Discussions is gone?

### ISSUE THREAD

**Issue by mkammes** [djdd87/SynoAI#112]
Surveillance Station 9.0 is in beta. Has there been any tinkering to see if SynoAI works?

This isn't an issue, so I was going to post in Discussions. Have Discussions been disabled?

Thanks!

**Comment by djdd87** [comment]
It's just me managing this project so I'd rather keep everything in one place for the time being. I've not tried the new Surveillance Station, no. To be honest, this is the first thing I've ever seen posted here that actually _would_ be a good use of discussions.

**Comment by djdd87** [comment]
I've renabled them.
