### ISSUE TITLE
SynoAI crashed when 1 camera not available to get snapshot

### ISSUE THREAD

**Issue by bdormael** [djdd87/SynoAI#123]
Sometimes it happens that 1 of my 13 camera's are not available (network issues) and therefore not reachable for getting a snapshot.
When SynoAI wants to retrieve a snapshot it then gets into an exception (see screenshot) and the complete SynoAI app crashes.

Can you handle the exception that if 1 or more camera fails that it continues with the rest and the app doesn't crash ?
<img width="896" alt="image" src="https://user-images.githubusercontent.com/12784886/161020849-72e60e79-f66c-46e1-850e-15b091e441f8.png">

**Comment by djdd87** [comment]
Yep - not a problem. I'll have a look into it.

**Comment by djdd87** [comment]
Fixed in `v1.2.0`
