### ISSUE TITLE
synoai docker container exits (139) on attempted start

### ISSUE THREAD

**Issue by filthyrake** [djdd87/SynoAI#136]
Attempting to run the (totally fresh and new) docker container results in an exit (139) with the following log output.  I am a bit at a loss.

warn: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
      Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
      No XML encryptor configured. Key {1d0af13d-574a-4b36-bd61-2867ae47c41a} may be persisted to storage in unencrypted form.
fail: SynoAI.Services.SynologyService[0]
      An unhandled exception occurred initialising SynoAI. Exiting...
      System.NullReferenceException: Object reference not set to an instance of an object.
         at SynoAI.Services.SynologyService.InitialiseAsync() in /src/Services/SynologyService.cs:line 307
crit: Microsoft.AspNetCore.Server.Kestrel[0]
      Unable to start Kestrel.
      System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
         at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Unhandled exception. System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at SynoAI.Program.Main(String[] args) in /src/Program.cs:line 11

**Comment by filthyrake** [comment]
I'm just dumb.  empty configs for cameras/notifiers cause it to break

**Comment by djdd87** [comment]
Hah - I was about to reply and say it was due to no cameras. I've pushed a change to prevent it erroring and to give an informative warning before stopping the app gracefully.

**Comment by djdd87** [comment]
>v1.2.0

**Comment by djdd87** [comment]
Fixed in `v1.2.0`
