### ISSUE TITLE
Exclusion not working when specifying exclusion zone co-ordinates "backwards"

### ISSUE THREAD

**Issue by Neocramencer** [djdd87/SynoAI#141]
Hi,

i defined an exclusion zone which seems not to be working. Config:

{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },

  "Url": "xxx",
  "User": "xxx",
  "Password": "xxx",

  "MinSizeX": 50,
  "MinSizeY": 50,
  
  "BoxColor": "#FF0000",
  "FontColor": "#FF0000",
  "FontSize": 20,	
  "Delay": 5000,
  "DrawMode": "Matches",
  "StrokeWidth": 3,
  "TextOffsetY": -25,
  "TextOffsetX": 0,
  "DrawExclusions": true,
  
  
  "AI": {
    "Type": "DeepStack",
    "Url": "http://192.168.0.200:83"
  },

  "Notifiers": [
{

  "Type": "Pushover",
  "ApiKey": "xxx",
  "UserKey": "xxx",
  "Sound": "siren"
}
  ],

  "Cameras": [
    {
      "Name": "Garten",
      "Types": [ "Person", "Cat", "Dog" ],
      "Threshold": 42,
      "MinSizeX": 50,
      "MinSizeY": 50,
	  "Exclusions": [
        {
            "Start": { "X": 2363, "Y": 853 },
            "End": { "X": 1888, "Y": 1404 }
        },
        {
            "Start": { "X": 1731, "Y": 853 },
            "End": { "X": 1886, "Y": 1152 }
        }
      ]
    }
  ]
}

Example Image:

![Garten_2022_08_02_10_46_26_343_1](https://user-images.githubusercontent.com/9692854/182341525-c68eab55-b6bf-470d-9e39-a6f402c0dbf5.jpeg)

Second: is it possible to also use anything different then rectengular for exclusion zones? As you see in my Capture with rect. boxes it is quite complicated to exclude.

Thanks and best regards Marc

**Comment by djdd87** [comment]
Hey, I think it's because you've defined your exclusion zones in a negative way. It's supposed to go from top left to bottom right, but you've done top right to bottom left. 

I should probably be able to account for this, but in the mean time, can you please try this:

```json
"Exclusions": [
  {
    "Start": { "X": 1888, "Y": 853 }, 
    "End": { "X": 2363, "Y": 1404 }
  },
  {
    "Start": { "X": 1731, "Y": 853 },
    "End": { "X": 1886, "Y": 1152 }
  }
]
```
I might be able to look into different shapes for exclusion zones using SKPath. I'll log an issue for it.

**Comment by Neocramencer** [comment]
Hi,

just see the green boxes above, this should be the exclusion zones or am i wrong? I enabled drawing the exclusion zones and the person is right in the zone.

Best regards

**Comment by djdd87** [comment]
Yes, those are the exclusion zones. But as I said, you've defined the zones backwards and there's a bug as I never accounted for anyone defining from top right to bottom left.

**Comment by Neocramencer** [comment]
Will do so and respond ;)

**Comment by Neocramencer** [comment]
![Garten_2022_08_03_09_02_36_668_1](https://user-images.githubusercontent.com/9692854/183046411-f88b1eef-7dfa-4a8b-9e76-5e41b0f30b63.jpeg)

Still not working correctly, but maybe there is an issue with multiple exclusion zones.

**Comment by Neocramencer** [comment]
![Garten_2022_08_02_20_08_25_356_1](https://user-images.githubusercontent.com/9692854/183046760-470ab43c-05cd-400e-a617-83262837d651.jpeg)

**Comment by djdd87** [comment]
Yeah I think you're right. You could just use the "Intersect" mode though instead of "Contains" which is the default:

"Start": { "X": 1888, "Y": 853 }, 
"End": { "X": 2363, "Y": 1404 },
"Mode": "Intersect"

It doesn't look like I've documented that option in the readme.

**Comment by Neocramencer** [comment]
under each exclusion zone or just the first?

**Comment by djdd87** [comment]
The setting is per exclusion zone.

**Comment by Neocramencer** [comment]
Thanks for the feedback, i will try again ;)

**Comment by Neocramencer** [comment]
Tested your suggestion a few days now and it seems to work, so you can close the issue now :) when the more advanced exclusion zonr is possible i can switch to just one simple exclusion uonr. Thanks alot again.

**Comment by djdd87** [comment]
I'll close it when I get chance to fix the negative definitions of exclusions. It should work either way around really.
