### ISSUE TITLE
per-camera webhook calls

### ISSUE THREAD

**Issue by Stewie3112** [djdd87/SynoAI#143]
Hi, I'm probably missing something, but can't figure out how to call a certain home-assistant push webhook. Right now I have 3 cameras configured and they call the same webhook every time a person is detected. Works fine, but this way i can't figure out which camera detected motion through HA, as there's no distinction between calls.

**Comment by djdd87** [comment]
Just define three different notifiers for each of your HA webhooks, then specifier the applicable notifier on each camera.

**Comment by Stewie3112** [comment]
I already have 3 different notifiers, but every event from any camera triggers them all. Is there an option in the camera section to specify a notifier to use?

**Comment by djdd87** [comment]
Yes. Look at the readme. Specify the notifiers to use per camera.

**Comment by Stewie3112** [comment]
Oh damn, sorry but I did't find that before, I was looking under the camera section XD.

Thanks a lot for this awesome integration, you have my coffee.
