### ISSUE TITLE
Multiple Webhooks

### ISSUE THREAD

**Issue by 1onar** [djdd87/SynoAI#147]
Hi,
sorry if it's a dump question. But is it possible to set up a webhook for each camera?
I've trying to setup action rules and each action rule got its own web hook url.

**Comment by djdd87** [comment]
Yes, create a webhook notification for each URL, then put the camera name in the cameras array as per the example in the README.

**README:**

``` json
"Notifiers": [
  {
    "Type": "{Type}",
    "Cameras": [ "Driveway", "Garden"]
  }
]
```

**Example:**

``` json
"Notifiers": [
  {
    "Type": "Webhook",
    "URL": "https://server/url_1"
    "Cameras": [ "Camera1" ]
  },
  {
    "Type": "Webhook",
    "URL": "https://server/url_2"
    "Cameras": [ "Camera2" ]
  },
  {
    "Type": "Webhook",
    "URL": "https://server/url_3"
    "Cameras": [ "Camera3" ]
  }
]
```
