### ISSUE TITLE
Webhook to Surveillance station

### ISSUE THREAD

**Issue by alexfonseca** [djdd87/SynoAI#151]
Hi, I am using webhooks to try to get a notification thru ds cam.
If I use the webhook directly in the browser it works perfectly, but thru the SynoAI, I can see it was triggered correctly but no action on ds cam.
Even though I get in the docker history a "Webhook: Success with HTTP status code 'OK'.", no alert triggered.

....
  "Notifiers": [
    {
      "Type": "Webhook",
      "Url": "http://192.168.1.253:5000/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method=Incoming&version=1&token=YkJpnzV9ValxR9BiZrM5UpH7jQPh4LTSftnTEFoh9v5UpPbo16cnH2D9SpB7Bgs7",
      "Method": "POST",
      "Field": "image",
      "Cameras": [ "Garagem" ]
    },
......

I have one for each 9 cameras

**Comment by djdd87** [comment]
Try using GET instead of POST.

**Comment by alexfonseca** [comment]
Great, just to let you know it worked perfectly.
