### ISSUE TITLE
Better AI/Custom Models

### ISSUE THREAD

**Issue by Akandesh** [djdd87/SynoAI#159]
I use SSS just to see when my cat wants to be let indoors and to my disappointment deepstacks cat model seems quite lacking and isn't confident at all with my cat so if we were able to create our own models it would be a lot more useful. 

[13% cat](https://cdn.discordapp.com/attachments/647548263553302566/1032324863051956264/CatCam_2022_10_19_16_10_26_554_1.jpeg)

**Comment by djdd87** [comment]
Already logged a few times, so closing. #117 #158 #82

You could try CodeProject.AI-Server as apparently that just works already in place of DeepStack although I've not had time to test it.
