### ISSUE TITLE
Crashing from 502 response

### ISSUE THREAD

**Issue by Akandesh** [djdd87/SynoAI#165]
Been working great for over a week and the past few days it started crashing almost every time it tried to do its thing. The issue seems to come and go but right now its constant. I've checked the codeproject-ai-servers logs and all seems normal and going to the same url as I have in the config I get to the control panel and are able to test the algorithm which works. 

Here's a picture of the logs: https://owned.lol/ak/tmp/yBlsCeJ8.png?k=tXTkF

**Comment by djdd87** [comment]
The error is happening when fetching the camera's current snapshot. Synology's server is returning a 502 (bad gateway) error, so the error is on their end or down to your network configuration. This isn't a SynoAI problem, so unfortunately I can't provide any suggestions.

**Comment by djdd87** [comment]
Closed as no further info/feedback provided.
