### ISSUE TITLE
Temporary exclusion of valid predictions on subsequent detection events

### ISSUE THREAD

**Issue by bristolm** [djdd87/SynoAI#168]
When a new object moves into frame and stops it will be identified unless it is filtered out by static exclusion zones each time a new movement event is passed long by Synology.  So, for example - a newly parked car can be repeatedly detected even though it hasn't moved.  This gets noisy if the camera isn't good at filtering out stuff like wind or shadows.

This suggestion is to create a _temporary_ exclusion zone for each valid prediction until that prediction is no longer valid.  This way there are only 2 notifications for each stationary object - when it first appears, and when it disappears.

I've actually coded this up as a new _ExcludeIdlePredictions_ boolean on Camera if you are interested.

**Comment by djdd87** [comment]
Hey, I'd actually already logged this as #111. If you've got some code, I'd definitely be interested in seeing your solution.

**Comment by bristolm** [comment]
Ah nuts!  My bad.  I'll close this one as DUPLICATE of #111 then.

Sure.  I can push what I have now.
