### ISSUE TITLE
After an update, the Action Rules in Synology need to be disabled and re-enabled to restart object detection

### ISSUE THREAD

**Issue by delprimero** [djdd87/SynoAI#177]
I last had this issue when the 1.2.1 release was rolled out and my alerts stopped running after the container updated. I could see that Surveillance Station was still detecting motion but then nothing was being sent to SynoAI. Going to Surveillance Station > Highlighting any relevant rules > Marking them as disabled and then re-enabling them, fixed the issue.

This may be only something that I have as a problem but putting this up here for others, just in case.

**Comment by djdd87** [comment]
Thanks for the info. As this sounds like a SSS issue and I've not experienced this myself or heard of anyone else reporting it, I'll just close it off. If anyone does report it, I'll point them to this issue.
