### ISSUE TITLE
Exclusions not working

### ISSUE THREAD

**Issue by JohannCR** [djdd87/SynoAI#180]
Hi,
I can't seem to make the exclusion zones work.
using
"DrawMode": "off",
"DrawExclusions": true,

And yet detected objects are drawn but not exclusion zones.
Is there an error in my config ?
Thanks

```
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Warning"
    }
  },
  "Url": "http://xxx:xxx",
  "User": "xxxx",
  "Password": "xxxx",
  "SaveOriginalSnapshot": "off",
  "DaysToKeepCaptures": 30,
  "AI": {
    "Type": "DeepStack",
    "Url": "http://xxx:xxx"
  },
  "Notifiers": [
    {
      "Type": "Webhook",
      "Url": "http://xxxx:xxx/api/webhook/mouvement_entree",
      "Cameras": ["Entree"],
      "Types": ["Person"]
    },
    {
    	"Type": "Webhook",
    	"Url": "http://xxxx:xxx/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method=Incoming&version=1&token=xxxx",
    	"Method":"GET",
    	"Cameras": ["Entree"]
    },
    {
      "Type": "Webhook",
      "Url": "http://xxxx:xxxx/api/webhook/cat_front_door",
      "Cameras": ["Entree"],
      "Types": ["cat", "dog"]
    }
  ],
  "Cameras": [
    {
      "Name": "Entree",
      "Types": ["person", "cat", "dog"],
      "Threshold": 70,
      "DrawMode": "off",
      "DrawExclusions": true,
      "Wait": 500,
      "MinSizeX": 20,
	  "MinSizeY": 20,
	  "Exclusions": [
        {
            "Start": { "X": 1800, "Y": 400 },
            "End": { "X": 2350, "Y": 900 },
            "Mode": "Intersect"
        }
    ]
    }
  ]
}
```

**Comment by djdd87** [comment]
I would expect that to work and draw the exclusion zones. Are you sure your image is high quality enough to be that many pixels? Can you try and set a test zone that's guaranteed to appear, e.g:

```json
        {
            "Start": { "X": 0, "Y": 0},
            "End": { "X": 100, "Y": 100},
            "Mode": "Intersect"
        }
```

**Comment by JohannCR** [comment]
No change. And the person box is drawn while it shouldn't

**Comment by djdd87** [comment]
Are you restarting SynoAI after changing the config values?

**Comment by JohannCR** [comment]
Yes of course. I'll check that my config is correctly saved and try by stopping and starting instead of restarting

**Comment by JohannCR** [comment]
Nope. No change. Config correctly saved and container restarted.

**Comment by JohannCR** [comment]
Maybe a config parameter variable type ? String/boolean

**Comment by JohannCR** [comment]
Do you need any log to help see what is going on ?
Maybe the entire config (got other cameras, maybe there could be a conflict ?)

**Comment by djdd87** [comment]
I've just seen why. You've put DrawMode and DrawExclusions against the camera config. They exist at the top level of the config, not under the camera.

**Comment by JohannCR** [comment]
Damn I new I made some stupid mistake^^
Thanks for this, it works fine now !
