### ISSUE TITLE
host cifs mount points write errors

### ISSUE THREAD

**Issue by pinomat81** [djdd87/SynoAI#183]
Hello,

I tried to use a CIFS volume mounted on Debian host and SynoAI docker to store SynoAI snapshots. 
When SynoAI is triggered by SSS, folders are created on CIFS folder but SynoAI generates the error below :
`Unhandled exception. System.UnauthorizedAccessException: Access to the path '/app/Captures/Front/Front_2023_03_03_21_09_25_987_Original.jpeg' is denied.
 ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.WriteSpan(ReadOnlySpan`1 source)
   at System.IO.FileStream.Write(Byte[] array, Int32 offset, Int32 count)
   at SkiaSharp.SKManagedWStream.OnWrite(IntPtr buffer, IntPtr size)
   at SkiaSharp.SKAbstractManagedWStream.WriteInternal(IntPtr s, Void* context, Void* buffer, IntPtr size)
`
All snapshots are created with 0 size. 
`root@codeprojectai:/# ls -l /opt/pve_volatile/102/Captures/Front/
total 4
-rwxr-xr-x 1 1060 users 0 Mar  3 21:03 Front_2023_03_03_21_03_46_175_Original.jpeg
-rwxr-xr-x 1 1060 users 0 Mar  3 21:05 Front_2023_03_03_21_05_22_255_Original.jpeg
-rwxr-xr-x 1 1060 users 0 Mar  3 21:06 Front_2023_03_03_21_06_49_727_Original.jpeg
-rwxr-xr-x 1 1060 users 0 Mar  3 21:09 Front_2023_03_03_21_09_25_987_Original.jpeg
-rwxr-xr-x 1 1060 users 2 Mar  3 21:07 sss.ddd
root@codeprojectai:/#`

When removing the docker volume binding _mount point_ --> _/app/Captures_ , all snapshots are generated correctly.

I checked with other dockers and do not have any issues.
I tried to create a CIFS docker volume without any luck.
I tried to create SynoAI with PUID/PGID (and different IDs) without any luck.

Regards

**Comment by djdd87** [comment]
Did you get to the bottom of this issue?

**Comment by pinomat81** [comment]
Sure, i ended to solve my problem. How ? I can't remember what I did to solve this issue :(

**Comment by pinomat81** [comment]
@djdd87 ,

Hello, I am sorry to reopen this ticket. But I know now how I solved my problem : I used a workaround that was to not use local folder and not cifs folder for Captures files.

Actually I tried to move this week my docker to a new docker server. I wanted to keep my existing Captures folder. After mounting cifs, the error showed up immediately. I passed hours to test docker+cifs settings (privileges, add_caps, file_mode, ...) without success. 
I can certifiy that there is no issue to write to Captures cifs folder from the docker host and from within the docker . I ended to move from cifs mount folder to AFS mount folder . This is not really what I want and this is not a good idea but mounting Captures folder with NFS works perfectly. 

I found an possible explanation here : https://github.com/dotnet/runtime/issues/42790 . It seems to be the method used to write captures files that causes these errors.
I don't know if you could look at it or help me in any way.

Thank you

**Comment by pinomat81** [comment]
@djdd87 ,

Hello, I am sorry to reopen this ticket. But I know now how I solved my problem : I used a workaround that was to not use local folder and not cifs folder for Captures files.

Actually I tried to move this week my docker to a new docker server. I wanted to keep my existing Captures folder. After mounting cifs, the error showed up immediately. I passed hours to test docker+cifs settings (privileges, add_caps, file_mode, ...) without success.
I can certifiy that there is no issue to write to Captures cifs folder from the docker host and from within the docker . I ended to move from cifs mount folder to AFS mount folder . This is not really what I want and this is not a good idea but mounting Captures folder with NFS works perfectly.

I found an possible explanation here : https://github.com/dotnet/runtime/issues/42790 . It seems to be the method used to write captures files that causes these errors.
I don't know if you could look at it or help me in any way.

Thank you

**Comment by pinomat81** [comment]
@djdd87 

I finally found a workaround (point 5). I don't know if you can do something but know. Below is a part of the whole story...

1. Host side

```
root@docker:~# cat /etc/fstab | grep  docker_volatilesmb
//dsm.domain.name/docker_volatile /mnt/docker_volatilesmb cifs user=user,password=******,domain=domain.name,vers=3.0,rw
 
root@docker:~# mount -l | grep docker_volatilesmb
//dsm.domain.name/docker_volatile on /mnt/docker_volatilesmb type cifs (rw,relatime,vers=3.0,cache=strict,username=user,domain=domain.name,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.60.100,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=4194304,wsize=4194304,bsize=1048576,echo_interval=60,actimeo=1,user=user)

root@docker:~# echo hello > /mnt/docker_volatilesmb/file1.txt
//dsm.domain.name/docker_volatile on /mnt/docker_volatilesmb type cifs (rw,relatime,vers=3.0,cache=strict,username=user,domain=domain.name,uid=0,noforceuid,gid=0,noforcegid,addr=192.168.60.100,file_mode=0755,dir_mode=0755,soft,nounix,serverino,mapposix,rsize=4194304,wsize=4194304,bsize=1048576,echo_interval=60,actimeo=1,user=user)

root@docker:~# cat /mnt/docker_volatilesmb/file1.txt
hello
root@docker:~# 
```
--> No problem

2. docker side

```
root@docker:~# docker exec -it cctv-synoai /bin/bash

root@cctv-synoai:/app# echo coucou > /app/Captures/file.txt
root@cctv-synoai:/app# cat /app/Captures/file.txt
coucou
root@cctv-synoai:/app#
```
--> No problem

But when I trigger the action rule to simulate a motion detection and it try to save the capture in /app/Captures, I get :
```
root@cctv-synoai:/app# ls Captures/Garage/Garage_2023_12_03_22_38_06_862_Original.jpeg -ln
-rwxr-xr-x 1 0 0 0 Dec  3 22:38 Captures/Garage/Garage_2023_12_03_22_38_06_862_Original.jpeg
root@cctv-synoai:/app#
```


#From the host side, the file has the correct uid/gid mapping 
```
root@ds918p:~# ls /volume1/docker_volatile/cctv/synoai/Captures/Garage/ -ln
total 0
----------+ 1 1298138246 1298137601 0 Dec  3 22:38 Garage_2023_12_03_22_38_06_862_Original.jpeg

```

3. Part of docker-compose
```

  synoai:
    image: djdd87/synoai:latest
    hostname: cctv-synoai
    container_name: cctv-synoai
    ports:
      - "0.0.0.0:8880:80"
    volumes:
      - /mnt/docker/cctv/synoai/appsettings.json:/app/appsettings.json:ro
      - /mnt/docker_volatilesmb/cctv/synoai/Captures:/app/Captures:rw
```

4. Tests

- Tried fstab options with different values gid,uid,noserverino,multiuser,fsc,cifsacl,file_mode,dir_mode,cache  -> failed
- Tried changing uid and gid of _apt inside the docker...  -> failed
- Tried to change multiple values of PUID and PGID in docker compose -> failed
- Mount a cifs folder from proxmox to the file server and create an image to store these captures files and mount the image as a disk of the VM -> works great but is overkill


5. Workaround

Source : https://forums.docker.com/t/a-workaround-for-net-writing-to-cifs-volume-yielding-empty-file-and-access-to-the-path-is-denied/110872

When mounting the cifs share in /etc/fstab, add the option "nobrl" to the mounting point !
`
before 
//server_fqdn/shared_folder /mnt/shared_folder cifs vers=3.0,rw,user=username,password=password,domain=domain.name
after
//server_fqdn/shared_folder /mnt/shared_folder cifs vers=3.0,rw,user=username,password=password,domain=domain.name,**nobrl**
`

Have a good night

**Comment by djdd87** [comment]
Apologies but not much of this means a lot to me! I know the docker image used is an old version (.Net 5). During the rewrite this will be bumped to a .Net 8 image, so potentially this'll help resolve whatever this issue is.
