### ISSUE TITLE
Intersect zone doesn't exclude objects from analyze

### ISSUE THREAD

**Issue by Charles-Em** [djdd87/SynoAI#188]
Hello,

First, thank you for your work, it's very appreciated and useful for me.
I've configured SynoAI with CodeProject as I couldn't get deepstack to work.

Codeproject is working fine and I get my pictures analysed correctly.
There are some zones I want to exclude but I can't get it to work.
Maybe I didn't understand some of it, so here are my settings:

1. Camera resolution is 3840*2160
2. Intersect config is :
        {
            "Start": { "X": 2570, "Y": 1730 },
            "End": { "X": 2680, "Y": 1830 },
			"Mode": "Intersect"
        }
3. The vehicle which has a part in this zone was still detected : https://prnt.sc/BfERGGP_nTep

Is there something I missed?

Kind Regards
Charles-Em

**Comment by djdd87** [comment]
Sorry I missed this. Can you provide the actual image with the exclusion zone borders and explain what you're expecting to happen?
