### ISSUE TITLE
Automatically delete images after a certain timeframe

### ISSUE THREAD

**Issue by djdd87** [djdd87/SynoAI#19]
From [reddit comment](https://www.reddit.com/r/synology/comments/kx6i37/synoai_surveillance_station_object_detection/gms7694?utm_source=share&utm_medium=web2x&context=3):

> 5. Another enhancement could be to delete the pictures folder after X number of days.

**Comment by AlexanderSch90** [comment]
a little Workaround: Install the Docker Image [ofelia](https://github.com/mcuadros/ofelia) and make a job like:

```
[job-exec "synoai delete"]
schedule = @every 3h
container = synoai
command =  find /app/Captures -iname "*" -mtime +14 -delete
```

**Comment by JohannCR** [comment]
@AlexanderSch90 Nice workaround, thanks. Can you explain the command ?
Say if I want to clean up every month all captures older than 30 days would that work ?
`[job-exec "synoai delete"]
schedule = @monthly
container = synoai
command =  find /app/Captures -iname "*" -mtime +30 -delete`

**Comment by AlexanderSch90** [comment]
Sure but monthly + 30 days is nearly 2 month. 
I would use @daily

**Comment by JohannCR** [comment]
@AlexanderSch90 coming back for some help, I cannot make ofelia work...
Seems like a socket issue but I don't what what to do with [this suggestion](https://github.com/mcuadros/ofelia/issues/155), can you help ? Thanks

**Comment by AlexanderSch90** [comment]
I think it is a Problem with Synology Docker. I run this on an Real Docker Server. Sry no idea...

**Comment by JohannCR** [comment]
Found another way to do it using the synology task scheduler.
For those who need it here is the command used :

find /volume1/docker/synoAI/captureDir -type f ! -mtime -30 -exec rm {} \;
