### ISSUE TITLE
Deepstack Dead? 

### ISSUE THREAD

**Issue by gurrie** [djdd87/SynoAI#190]
Hi, 

Firstly thank you for creating this fantastic project, I have found it to be super useful. I wanted to ask if you have any plans to support other AI servers apart from Deepstack? I may be wrong but the project seems to be dead.

Thanks again
Brian

**Comment by djdd87** [comment]
Hey, you can use CodeProject-AI currently. It's very similar to DeepStack. Do you have any suggestions of which AIs to use? There's already a task logged for Google's Coral AI.

**Comment by gurrie** [comment]
TBH I completely missed that the project supports CodeProject-AI currently, my apologies. I will give that a go! Thanks again.
