### ISSUE TITLE
Logs show Deepstack usage, but CodeProject is being used

### ISSUE THREAD

**Issue by mkammes** [djdd87/SynoAI#193]
appsettings.json:

![image](https://github.com/djdd87/SynoAI/assets/8660699/0f64ec62-b48c-48d5-afc2-649ff9f4ba94)

Synology Logs:
![image](https://github.com/djdd87/SynoAI/assets/8660699/bb04e648-c3a4-4f98-a8c0-1c3e08e0a883)

I can also confirm that Deepstack has long been uninstalled and removed from Docker.

**Comment by sanderdewit** [comment]
this should be resolved with the latest commits
