### ISSUE TITLE
docker-image.

### ISSUE THREAD

**Issue by sanderdewit** [djdd87/SynoAI#198]
Thanks for commiting the fork changes.
I did make one mistake. the [docker-image.yml](https://github.com/djdd87/SynoAI/blob/main/.github/workflows/docker-image.yml)
now is modified, but should be changed back to 

change      run: docker build -t dewitauto/synoai-fork:latest SynoAI
to      run: docker build -t djdd87/synoai:latest SynoAI
change
      run: docker push dewitauto/synoai-fork:latest
to
      run: docker push djdd87/synoai:latest

Apologies for this.

**Comment by djdd87** [comment]
Thanks, all sorted.
