### ISSUE TITLE
In the last week, Telegram messages no longer specify the type of object recognized.

### ISSUE THREAD

**Issue by mkammes** [djdd87/SynoAI#199]
Former Telegram message(up until September 16th)

Telegram Message:
"Motion detected on [Camera Name]."

[Camera thumbnail with object outline and object type]

Detected 1 Objects:
Person:"

Current Telegram Message:
"Motion detected on [Camera Name]."

[Camera thumbnail with object outline and object type]

Detected 1 Objects:"

The type of object is no longer present in the Telegram text part of the message, but *is* still present in the camera thumbnail.

I'm unable to find any updates that were applied to the environment to cause this change (I was out of town, I swear!)

Syno AI v1.2, with Synology Surveillance Station. Using CodeProject AI Server 2.2.4-Beta (the omission of Object type was happening in the previous version, too).

**Comment by djdd87** [comment]
Do you have anything that automatically pulls the latest image? I accepted a few PRs a few days ago and haven't properly tested them yet.

**Comment by ichbinrodolf** [comment]
Hi, same issue here, this seems a regression as object type was given before. I do have watchtower that pulls latest images indeed.
![image](https://github.com/djdd87/SynoAI/assets/7933016/fa5d64bb-9630-4e5b-99e7-09c938ead5b3)

**Comment by mkammes** [comment]
I also am using Watchtower, @ichbinrodolf .

**Comment by djdd87** [comment]
Can you try again on the latest image? I've reverted the PRs that caused these issues.
