### ISSUE TITLE
Synoai stops

### ISSUE THREAD

**Issue by Petran54** [djdd87/SynoAI#200]
Hello,

For a while now, my synoai in Docker on the Synology NAS has started restarting at frequent intervals.

Been using codeproject-ai-server but switched to Deepstack with no difference.

Docker is rebooted and re-introduced by Synoai, Deepstack and ai-server.

Not good when things go wrong without you immediately knowing and you have no surveillance.

What could be wrong? Looks like something with logging. Maybe when it has to delete older capture than 14 days?

Sincerely
Peter
Sweden

Log
(Last ät top)

[Synoai_log.txt](https://github.com/djdd87/SynoAI/files/12709481/Synoai_log.txt)

**Comment by djdd87** [comment]
The error looks like it's around the formatting of the deletion info messages. I've had a few problems since accepting a few pull requests, so I've reverted the PRs. I've also added an error handler around the task as well so it'll log an error instead of taking down the entire app. Let me know how you get on now.

**Comment by Petran54** [comment]
Downloaded and installed. Now it runs without stopping. Seeing two warnings and an error in api calls to Deepstack. Don't know how to interpret it and if it's wrong on my end. Just quickly switched from ai server to Deepstack.

<img width="1024" alt="image" src="https://github.com/djdd87/SynoAI/assets/36693421/2055e88e-4cb9-455c-97bb-2389628c5426">

... and last

<img width="1061" alt="image" src="https://github.com/djdd87/SynoAI/assets/36693421/412f8a1b-b6b5-4e0c-9618-4d9daa699657">

**Comment by Petran54** [comment]
More api-error but the app still running.

I change to ai-server to see ...

<img width="1038" alt="image" src="https://github.com/djdd87/SynoAI/assets/36693421/a3d0421a-9e7b-4cf0-8962-bab22cad8680">

**Comment by djdd87** [comment]
The failed to call API warning is because you haven't set up the docker image properly. You need to enable vision detection, please see the trouble shooting section in the readme.

**Comment by Petran54** [comment]
Ok, I see ... now with ai-server all is up and running.

Thank you!

//Peter

<img width="1830" alt="image" src="https://github.com/djdd87/SynoAI/assets/36693421/631e74ee-468a-43db-b924-a9ee69face95">
