### ISSUE TITLE
Not able to startup synoai container: Receiving Login: Failed due to HTTP status code 'BadRequest'

### ISSUE THREAD

**Issue by abhwang** [djdd87/SynoAI#205]
I've configured the appsettings.json per the example with the user and pass set to the account I created within Synology Surveillance Station. Upon trying to start the synoai container, it immediately crashes with log messages such as: "API: Failed due to HTTP status code 'BadRequest'" and "Login: Failed due to HTTP status code 'BadRequest'"

**Comment by JoeyJoe6** [comment]
post your appsettings.json file here. Also within Synology SS, did you create a new user account or are you using an existing account?

**Comment by abhwang** [comment]
Appsettings.json provided with username, password, and Pushbullet API key redacted.
I created a brand new user account within Synology SS and verified the password is correct.
Also included a screenshot of the output log from Container Manager.

![Capture](https://github.com/djdd87/SynoAI/assets/61101242/744e1a2a-0278-4d53-8bad-622cb7c32683)
[appsettings.json](https://github.com/djdd87/SynoAI/files/13184904/appsettings.json)

**Comment by djdd87** [comment]
Is 5001 your DSM port? It's usually 5000 by default.

**Comment by djdd87** [comment]
5001 is for HTTPS and you're using HTTP:

  "Url": "http://192.168.1.50:5001",

**Comment by abhwang** [comment]
Ahh, that was the issue. I'm dumb for not seeing the port number was set to use HTTPS. Thanks for identifying the issue!
