### ISSUE TITLE
Crashes after last DSM update

### ISSUE THREAD

**Issue by Cavekeeper** [djdd87/SynoAI#207]
synoai:latest crashes after the last update to DSM 7.2.1-69057 Update 1 from 10/31/23
The container stops. Even if the image is reloaded and installed.
Here is the protocol
`

date | stream | content
-- | -- | --
2023/10/31 13:11:50 | stdout | Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
2023/10/31 13:11:50 | stdout | [40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]
2023/10/31 13:11:42 | stdout | at SynoAI.Services.SynologyService.InitialiseAsync() in /src/Services/SynologyService.cs:line 285
2023/10/31 13:11:42 | stdout | at SynoAI.Services.SynologyService.GetEndPointsAsync() in /src/Services/SynologyService.cs:line 62
2023/10/31 13:11:42 | stdout | at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
2023/10/31 13:11:42 | stdout | --- End of inner exception stack trace ---
2023/10/31 13:11:42 | stdout | --- End of inner exception stack trace ---
2023/10/31 13:11:42 | stdout | at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
2023/10/31 13:11:42 | stdout | at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2023/10/31 13:11:42 | stdout | at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
2023/10/31 13:11:42 | stdout | at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2023/10/31 13:11:42 | stdout | at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2023/10/31 13:11:42 | stdout | at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
2023/10/31 13:11:42 | stdout | at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
2023/10/31 13:11:42 | stdout | ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
2023/10/31 13:11:42 | stdout | ---> System.TimeoutException: The operation was canceled.
2023/10/31 13:11:42 | stdout | System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
2023/10/31 13:11:42 | stdout | An unhandled exception occurred initialising SynoAI. Exiting...
2023/10/31 13:11:42 | stdout | [41m[30mfail[39m[22m[49m: SynoAI.Services.SynologyService[0]
2023/10/31 13:10:01 | stdout | No XML encryptor configured. Key {bf246acf-ddff-466b-987d-3e64132763cd} may be persisted to storage in unencrypted form.
2023/10/31 13:10:01 | stdout | [40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
2023/10/31 13:10:01 | stdout | Storing keys in a directory '/root/.aspnet/DataProtection-Keys' that may not be persisted outside of the container. Protected data will be unavailable when container is destroyed.
2023/10/31 13:10:01 | stdout | [40m[1m[33mwarn[39m[22m[49m: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[60]

`

**Comment by JoeyJoe6** [comment]
What version of DSM did you upgrade from?
Im running that DSM version with no issues. I had to backup my docker configs from an older DSM version and reimport since DSM switched from "docker" to "container manager"

**Comment by Cavekeeper** [comment]
Version 7.2 was previously installed. Synoai also worked without any problems. With the update to 7.2.1 the problems now exist. Synoai Container runs for 1 minute and then crashes. I also renewed the container and the image. Except the config, of course.

**Comment by JoeyJoe6** [comment]
only thing that pops out from the log clip you provided is "The request was canceled due to the configured HttpClient.Timeout". 
If you have a separate user account that synoai uses to connect to your DSM? prehaps its locked out? Also you can change mod your loglevel in the Default area from "information" to "debug" That may provide an return code to help

**Comment by djdd87** [comment]
From the readme:

![image](https://github.com/djdd87/SynoAI/assets/22151993/ca968319-305f-45b5-b0ea-30f766cc3df4)

Perhaps this is relevant?

**Comment by Cavekeeper** [comment]
Actually, it was a firewall problem. After I turned it off, the app ran perfectly. So I have now added a permitted Docker network to the firewall. Now everything is back to normal. I just don't understand why everything worked before the DSM update. I never changed anything on the firewall. In any case, we can mark this case as solved. Many thanks for the help!
