### ISSUE TITLE
Add the ability to define exclusion/inclusion areas in the configs

### ISSUE THREAD

**Issue by djdd87** [djdd87/SynoAI#21]
I'm still finding that people walking passed the front of the house on the road is triggering events. This occurs because SurveillanceStation just so happens to detect motion inside the required boundaries at the same time someone walks passed. i.e. I've defined in SS that it shouldn't trigger motion on the road, however motion on the driveway, e.g. a sudden change in sunlight/a leaf blowing across/a butterfly sneezing, still triggers the action. That action that fires and SynoAI checks the image and _occasionally_ at that moment in time a person is walking by.

I propose adding an array of co-ordinates to ignore certain areas - or maybe it'd be better to include certain areas.

For example:

The following would exclude any objects detected by the AI in a box in the image starting at the pixels 10,10 to 50,100.
```json
Exclusions: [
  {
     "StartX": 10,
     "StartY": 10,
     "EndX": 50,
     "EndY": 100
  }
]
```

**Comment by Ewarren7** [comment]
This would be very helpful. 
It actually appears to be a feature in Christopher Adams' sssAI - ([camera config](https://github.com/Christofo/sssAI/blob/f3855fe91bf7c099e57245bf2b58776ccc052bc6/config/cameras.json#L6) & [code](https://github.com/Christofo/sssAI/blob/abb69a8d0d18075ffb5bdeda1e04e0825516207c/app/main.py#L95)) that this was derived from. 

From what I can tell by briefly looking at it I think it is doing what you propose and just checking the deepstack response with the coordinates and then checking to see if the found object is within the predefined ignore area.

**Comment by eRJe79** [comment]
Wouldn't the same principle be able to rule out static objects?

From the readme:
Caveats:
Looking for an object, such as a car on a driveway, will continually trigger alerts if that object is in view of the camera when Surveillance Station detects movement, e.g. a tree blowing in the wind.

**Comment by djdd87** [comment]
Yeah that would work in theory.
