### ISSUE TITLE
slow receive of snapshot from DSM to synoai?

### ISSUE THREAD

**Issue by JoeyJoe6** [djdd87/SynoAI#210]
I have 1 camera in my mix that appears to take an excessive amount of time to send a snapshot to synoai when requested. All other cameras take approx 300ms, where this one is taking 20000ms++
Tried restarting synoai and the DSM server, deleted the problem camera and recreated, but no change. 
Any thoughts?

info: SynoAI.Controllers.CameraController[0]                                     
      cam2-alerts: Snapshot received in 20524ms.                                 
info: SynoAI.Controllers.CameraController[0]                                     
      cam2-alerts: Snapshot 1 of 1 received at EVENT TIME 20524ms.               
dbug: SynoAI.Services.AIService[0]                                               
      cam2-alerts: DeepStackAI: POSTing image with minimum confidence of 0.45 (45
%) to http://192.168.xxx.xxx:32168/v1/vision/detection.                           
dbug: SynoAI.Services.AIService[0]                                               
      cam2-alerts: DeepStackAI: Responded with {"message":"No objects found","count":0,"predictions":[],"success":true,"code":200,"command":"detect","moduleId":"ObjectDetectionNet","executionProvider":"DirectML","canUseGPU":true,"inferenceMs":479,"processMs":480,"analysisRoundTripMs":501}.                                  
info: SynoAI.Services.AIService[0]                                               
      cam2-alerts: DeepStackAI: Processed successfully (526ms).                  
info: SynoAI.Controllers.CameraController[0]                                     
      cam2-alerts: Snapshot 1 of 1 contains 0 objects at EVENT TIME 21050ms.     
info: SynoAI.Controllers.CameraController[0]                                     
      cam2-alerts: Nothing detected by the AI at EVENT TIME 21050ms.             
dbug: SynoAI.Controllers.CameraController[0]                                     
      cam2-alerts: No objects were detected by the AI exceeding the confidence level (45%) and/or minimum size (150x150 and/or maximum size (2147483647,2147483647))                                                                               
info: SynoAI.Controllers.CameraController[0]                                     
      cam2-alerts: Finished (21050ms).                                           
dbug: SynoAI.Controllers.CameraController[0]                                     
      cam2-alerts: Removing running camera block.

**Comment by djdd87** [comment]
Do you have all the timings from the log alongside those messages?

**Comment by djdd87** [comment]
Closing, no response.
