### ISSUE TITLE
Response status code does not indicate success: 502 (Bad Gateway)

### ISSUE THREAD

**Issue by jurgenvdven** [djdd87/SynoAI#211]
For some reason since a couple day's SynoAI is restarting multiple times a day. Before this SynoAI was running stable for 70 days without any issues.

![afbeelding](https://github.com/djdd87/SynoAI/assets/60699117/bd9b90e2-0eb8-4811-82cf-28bccfd4d3f0)

What I did to try to resolve:
- Restart Surv station
- Created a new SynoAI container with the same configuration (appsettings.json)

What can be the problem?

**Comment by djdd87** [comment]
Can you provide your config?

**Comment by jurgenvdven** [comment]
`{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Warning"
    }
  },

  "Url": "http://x.x.x.x:5000",
  "User": "",
  "Password": "",

  "MinSizeX": 100,
  "MinSizeY": 100,
  "DaysToKeepCaptures": 30,
  "DrawExclusions": true,
  "SaveOriginalSnapshot": "Always",
  
  "AI": {
    "Type": "DeepStack",
    "Url": "http://x.x.x.x:83"
  },

  "Notifiers": [
    {
	"Type": "Telegram",
	"ChatID": "",
	"Token": "",
	"PhotoBaseURL": ""
	}
  ],

  "Cameras": [
    {
      "Name": "buitencam",
      "Types": [ "Person"],
      "Threshold": 25,
      "MinSizeX": 50,
      "MinSizeY": 50
    },
        {
      "Name": "keuken",
      "Types": [ "Person"],
      "Threshold": 25,
      "MinSizeX": 50,
      "MinSizeY": 50
    }
  ]
}`

**Comment by jurgenvdven** [comment]
Yesterday changed logging level to debug and this morning the first crash.

![afbeelding](https://github.com/djdd87/SynoAI/assets/60699117/ded1de21-58e9-4f6e-81c4-e6db54d9b9ba)

**Comment by djdd87** [comment]
Sorry, there's nothing obvious there. I think this is a network issue or
another issue your side.

*Many thanks,*

*Daniel Done*
*+44(0)7970 161746*

**Comment by jurgenvdven** [comment]
I rebooted my NAS after that the issue is gone. Strange but the case can be closed.

Thanks
