### ISSUE TITLE
DeepStackAI: Failed to call API with HTTP status code 'Unauthorized'.

### ISSUE THREAD

**Issue by mkaltner** [djdd87/SynoAI#212]
As far as I can tell, everything is configured correctly but I keep getting unauthorized when testing my action rule.

Deepstack is up and running:

![image](https://github.com/djdd87/SynoAI/assets/4999672/d47563f5-5529-476e-b4b2-9b2242282445)

Deepstack-UI can talk to it:

![image](https://github.com/djdd87/SynoAI/assets/4999672/e89358fa-be0a-45d7-abf6-335236316912)

Deepstack UI Config points to 192.168.1.5:1500:
![image](https://github.com/djdd87/SynoAI/assets/4999672/ecc9197a-ebc7-4903-bd25-f6d537b1a3e6)

SynoAI is pointed to the same address:port:

![image](https://github.com/djdd87/SynoAI/assets/4999672/63394861-af43-4740-94b4-61e2db0d148d)

The Action rule can call SynoAI:

![image](https://github.com/djdd87/SynoAI/assets/4999672/ccff8a70-a790-4608-a5bf-3f2d796168ef)

But I get the following error(s):

![image](https://github.com/djdd87/SynoAI/assets/4999672/4a2c520a-d964-493d-a856-96286daeb74a)

Any idea on what's causing the unauthorized error?

Thanks!

**Comment by djdd87** [comment]
Is vision detection set on the environment variables?

**Comment by mkaltner** [comment]
Here are the ENV variable:

![image](https://github.com/djdd87/SynoAI/assets/4999672/16ec580a-2e84-4e75-aa8c-582e3ae75454)

**Comment by mkaltner** [comment]
I tweaked a couple things and it seems to be working now.  I had an empty api-key line that may have been causing the issue
