### ISSUE TITLE
Add the profileType for the Surveillance Station stream as an optional appSettings parameter

### ISSUE THREAD

**Issue by Martinnygaard** [djdd87/SynoAI#25]
Hi,

Great interface! I really like the fact only one action is needed from SSS - and the flexibility for notifications!
However, I am not getting any notifications out of SynoAI.
As you can see in the log here, it is receiving motion detection from SSS. Also, it sends the image to Deepstack, deep stack makes it analysis and returns the result (In this case, Person 99,8%).

What confuses me is that SyniAI then decides that "Nothing detected by the AI". I have set my confidence level to 45, and DeepStack return 99.8%.
Any ideas what Is happening?
```
2021-03-18 12:57:56,stdout,      Driveway_East: Motion detected, fetching snapshot.
2021-03-18 12:57:57,stdout,      Driveway_East: Taking snapshot
2021-03-18 12:57:59,stdout,      Driveway_East: Snapshot received   (2328ms).
2021-03-18 12:57:59,stdout,      SynoAI.Models.Camera: Processing.
2021-03-18 12:58:09,stdout,      Driveway_East: DeepStackAI: Processed   successfully (10165ms).
2021-03-18 12:58:09,stdout,      SynoAI.Models.Camera: person   (99.8577700%)
2021-03-18 12:58:09,stdout,      Driveway_East: Nothing detected by the   AI exceeding the defined confidence level
2021-03-18 12:58:09,stdout,      Driveway_East: Finished (12632ms).
```

Configuration.json:
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Warning"
    }
  },

  "Url": "http://192.168.0.55:5000",
  "User": "Smarthome",
  "Password": "MySuperDuperSecretPassword!",

  "AI": {
    "Type": "DeepStack",
    "Url": "http://192.168.0.55:83",
    "MinSizeX": 100,
    "MinSizeY": 100
  },

  "Notifiers": [
	{
	  "Type": "Pushbullet",
	  "ApiKey": "MySuperDuperSecretAPIkey!"
	},
    {
      "Type": "Webhook",
	  "Cameras": ["Driveway_East"],
      "Url": "http://192.168.0.55:8123/api/webhook/Driveway_East",
      "Method": "POST",
      "Field": "image"
    },
    {
      "Type": "Webhook",
	  "Cameras": ["Driveway_West"],
      "Url": "http://192.168.0.55:8123/api/webhook/Driveway_West",
      "Method": "POST",
      "Field": "image"
    },
    {
      "Type": "Webhook",
	  "Cameras": ["Yard_Front"],
      "Url": "http://192.168.0.55:8123/api/webhook/Yard_Front",
      "Method": "POST",
      "Field": "image"
    },
    {
      "Type": "Webhook",
	  "Cameras": ["Yard_Rear"],
      "Url": "http://192.168.0.55:8123/api/webhook/Yard_Rear",
      "Method": "POST",
      "Field": "image"
    }
  ],

  "Cameras": [
    {
      "Name": "Driveway_East",
      "Types": [ "Person", "Car" ],
      "Threshold": 45
    },
    {
      "Name": "Driveway_West",
      "Types": [ "Person", "Car" ],
      "Threshold": 45
    },
    {
      "Name": "Yard_Front",
      "Types": [ "Person", "Car" ],
      "Threshold": 45
    },
    {
      "Name": "Yard_Rear",
      "Types": [ "Person", "Car" ],
      "Threshold": 45
    }
  ]
}
```

**Comment by djdd87** [comment]
Hey, everything looks good from a config point of view.

The only reason that you'll get the message "Nothing detected by the   AI exceeding the defined confidence level" is if it calculates there are no "validPredications":

```csharp
IEnumerable<AIPrediction> validPredictions = predictions.Where(x =>
    camera.Types.Contains(x.Label, StringComparer.OrdinalIgnoreCase) &&     // Is a type we care about
    x.SizeX >= Config.AIMinSizeX && x.SizeY >= Config.AIMinSizeY)           // Is bigger than the minimum size
    .ToList();
```

So as I can see your types are correctly configured for the camera:

```csharp
"Types": [ "Person", "Car" ],
```

That suggests that the size of the object is less than 100x100 pixels... which sounds very odd considering the fact DeepStack is nearly 100% certain there's a person there.

Can you please try and set the minimum sizes to 0 and see if it works?

```json
    "MinSizeX": 0,
    "MinSizeY": 0
```

**Comment by Martinnygaard** [comment]
Thanks, I will try to adjust the size.
I have two streams on my Reolink RLC410 camera, and I do not know which stream it uses to object detection?
In the case of the 2nd stream, the square around me is 59x104
Most of my cameras is recording from a big distance, so persons will be quite small in the picture. But as long as deepstack kan identifies it, I guess it is good enough.

- Stream 1: 2460x1910 px
- Stream 2: 640x480 px

![image](https://user-images.githubusercontent.com/26490587/111635083-6c628580-87f7-11eb-907b-d0a54df7d3a5.png)

**Comment by djdd87** [comment]
By default it uses the "Balanced" stream as I've not specified the profileType and 1 is the default. (Note to myself - Page 55 of the functional spec https://global.download.synology.com/download/Document/Software/DeveloperGuide/Package/SurveillanceStation/All/enu/Surveillance_Station_Web_API.pdf)

As your person there is under 100 pixels on the X axis is'll be ignored.

I think it's worth me adding the profileType as config and the confidence detection from the AI should also include the X and Y dimensions for debugging purposes.

If you can confirm it works by setting the min x and y to 0, then I'll change this issue into a feature request to do the above.

**Comment by Martinnygaard** [comment]
That was it - thanks a lot!

![Driveway_East_2021_03_18_15_58_25_233](https://user-images.githubusercontent.com/26490587/111647998-417e2e80-8803-11eb-8e17-6ceb73cae9c2.jpeg)

**Comment by djdd87** [comment]
Great stuff - OK I'll update the issue then.

**Comment by djdd87** [comment]
@Martinnygaard it turns out I've already done this! It's just not in the readme. The config is called "Quality" and it can be one of:
- High
- Balanced
- Low

**Comment by Martinnygaard** [comment]
Like this?
```
 "Cameras": [
    {
      "Name": "Driveway_East",
      "Types": [ "person", "Car" ],
      "Threshold": 45
      "Quality": High
    },
    {
      "Name": "Driveway_West",
      "Types": [ "person", "Car" ],
      "Threshold": 45
      "Quality": High
    },
    {
      "Name": "Yard_Front",
      "Types": [ "person", "Car" ],
      "Threshold": 45
      "Quality": High
    },
    {
      "Name": "Yard_Rear",
      "Types": [ "person", "Car" ],
      "Threshold": 45
      "Quality": High
    }
  ]
```

**Comment by djdd87** [comment]
No, it's a top level config:

```json
"User": "",
"Password": "",
"Quality": "High"
``

Note that it's text, so you need to use double quotes around the value.
