### ISSUE TITLE
Notification: Add support for email notifications

### ISSUE THREAD

**Issue by djdd87** [djdd87/SynoAI#3]
Add the ability to send notifications as an email. Should ensure that the implementation works with both standard username/password credentials and OAuth/certificate based authentication.

**Comment by guitengyue** [comment]
Webhook for nodered need user and password
      "Type": "Webhook",
      "Url": "http://xxx:8123/api/webhook/xxx",
      "user": "xxx",
      "password": "xxx",
      "Method": "post",
      "Field": "image",
      "SendImage": true,
      "SendTypes": true
maybe the 'user' and 'password'  is wrong...what is the true one?

**Comment by djdd87** [comment]
@guitengyue - I'll raise this as a new enhancement for you. This enhancement is for the addition of authentication to webhooks, but this issue is for the addition of a notifier for emails.

**Comment by guitengyue** [comment]
> @guitengyue - I'll raise this as a new enhancement for you. This enhancement is for the addition of authentication to webhooks, but this issue is for the addition of a notifier for emails.

thank you very much!
but it's wrong  when  I  use the following format .
    {
       "Type": "Webhook",
       "Url": "http://xxx:8123/api/webhook/xxx",
       "Authorization": "Basic",
         "Username": "xxx",
         "Password": "xxx",
       "Method": "post",
       "Field": "image",
       "SendImage": true,
       "SendTypes": true
    }    
could you Write a case ？

**Comment by djdd87** [comment]
@guitengyue - please take this discussion to the other issue I raised if you need anything else as it's not relevant to this enhancement. However what you have above is correct. The issue is actually a problem with the docker image build due to a [NuGet certificates issue](https://github.com/NuGet/Announcements/issues/49). So basically the docker image you have doesn't have the latest changes I made yet.
