### ISSUE TITLE
Suggestion: MinX and MinY per camera

### ISSUE THREAD

**Issue by Martinnygaard** [djdd87/SynoAI#30]
Hi,

In my system I have 5 cams. (4x 5MP and 1x 12MP)
in my case, I have in the config set a min XY on 130x75px. - That is surfficiant for my 5MP camera to ignore a lamp, that would otherway be seen as a person (By deepstack).

Because the 12MP have a image size of 3840x2160, then the global setting of 130x75 is basically nothing.
If I increase global 130x75px minimum criteria, i will start to ignore real positives on the 5MP camera.

My suggestion is to move minXY settings to a per camera basis.
Or alternatively, IF minXY is defined on camera level, it will override the global setting.
That will give the optimal condition for fine-tuning each camera to its surrounding.
 - A bonus feature ill be to incorporate the "ignore area" feature of DeepStack.

I have been looking at it myself, and i would like to try figuring it out at some point, how it works - but I am very new in this programming language.
With some support, I might be able to help a bit out?

Example:
```
  "Cameras": [
    {
      "Name": "Driveway_East_5MP",
      "Types": [ "person" ],
      "Threshold": 45,
      "MinSizeX": 130,
      "MinSizeY": 75
    },
    {
      "Name": "Driveway_West_12MP",
      "Types": [ "person", "Car" ],
      "Threshold": 45
      "MinSizeX": 455,
      "MinSizeY": 200
    },
    {
      "Name": "Yard_Front_5MP",
      "Types": [ "person", "Car" ],
      "Threshold": 45
      "MinSizeX": 130,
      "MinSizeY": 75
    },
    {
      "Name": "Yard_Rear_5MP",
      "Types": [ "person", "Car" ],
      "Threshold": 45
      "MinSizeX": 130,
      "MinSizeY": 75
    }
  ]

```

**Comment by djdd87** [comment]
Good suggestion, thanks. It definitely makes sense having the min/max on a camera by camera basis, because they may very well be different resolutions as you've stated.

I would suggest having the AI min/max has a default and then each camera can have it's own to override that value.

If you'd like to have a go at doing it yourself, that's great. Basic steps for how I see it are:

- Add the MinSizeX/Y properties to the Camera class
- Where the existing AI MinX/Y values are passed to the AI, determine if there's an override on the camera
  - If there is then use the MinX/Y from the camera;
  - Otherwise use the AI default.

**Comment by djdd87** [comment]
Do you have a link to the documentation for "ignore area" on Deepstack? I don't see it on https://docs.deepstack.cc/.

**Comment by Martinnygaard** [comment]
No I haven't looked for it in documentation, but I use the "DeepStack UI" container for manually uploading images and adjusting properties, to reach the result I want.

And in that UI, it is possible to specify this ignore area, so my thought was:
If it is possible for that container to use these parameters in the API, it should be possible for SynoAI aswell.

**Comment by djdd87** [comment]
Yeah I can't see it in the docs. Issue #21 is already logged to do something similar for that. Would be cool to do it via the API instead though.

**Comment by Martinnygaard** [comment]
@djdd87, if I will try to modify for the "per camera" min XY, could I reach out to you in discord chat or something, if I got a question, or would you prefer to keep everything here?

**Comment by Martinnygaard** [comment]
> Yeah I can't see it in the docs. Issue #21 is already logged to do something similar for that. Would be cool to do it via the API instead though. I'll see if it's possible and just not documented.

Yes, that is exactly what I was referring to.
So this Issue #30 is exclusive for min XY pr camera. :-)

**Comment by djdd87** [comment]
Yep. Probably easiest if you have a go and post here. GitHub doesn't really have a private messaging feature for me to give you that info.

**Comment by djdd87** [comment]
Implemented and updated readme. Additionally changed AIMinSizeX and AIMinSizeY in the main config to be just called "MinSizeX" and "MinSizeY". This should be flagged as a breaking change, however there's no versioning yet for me to do so.
