### ISSUE TITLE
Can this also trigger recording on SSSAI

### ISSUE THREAD

**Issue by morgsman** [djdd87/SynoAI#31]
Hi - thanks for your work to make this available. Unless I misunderstand this it doesn't trigger recording on the Synology once it has matched an object via Deepstack? It just sends a rich notification. Perhaps you are assuming continuous recording on the Synology?

Would it be possible (like SSSAI does) to send a Webhook to Synology upon a successful identification of an object? I like to switch the recording to a higher quality when triggered currently via SSSAI. This would need to be configurable for each camera set up.

Also I noticed that if the camera name has spaces in the name then the action rule won't work e.g. "Front of House".

Many thanks

**Comment by djdd87** [comment]
Hey you can do that by just creating a trigger that starts a recording and then by calling that trigger using the API hook notification.

**Comment by morgsman** [comment]
With respect to the action rule. I had a camera called "Front of House". The following trigger failed.

192.168.0.x:8889/Camera/Front Of House

When I changed the camera name in Synology to "FrontOfHouse" the following trigger worked:

192.168.0.x:8889/Camera/FrontOfHouse

**Comment by morgsman** [comment]
I get what you are saying about triggering a web hook using the notification feature. However I have four cameras and so each camera has it's own unique web hook triggered action rule. If I use the notification Webhooks feature in the SynoAI settings file that can't be done for a specific camera can it?

**Comment by djdd87** [comment]
Can you post a screenshot of your action rule configuration? Most of my cameras have spaces in the name, e.g. Garden North, Garden South and they work fine.

**Comment by morgsman** [comment]
This is the version that works
<img width="655" alt="Screen Shot 2021-05-15 at 6 27 45 pm" src="https://user-images.githubusercontent.com/75959855/118353804-511fb680-b5ab-11eb-953f-1239bfe20827.png">

**Comment by djdd87** [comment]
> I get what you are saying about triggering a web hook using the notification feature. However I have four cameras and so each camera has it's own unique web hook triggered action rule. If I use the notification Webhooks feature in the SynoAI settings file that can't be done for a specific camera can it?

Just create 4 webhooks, one for each API trigger on Surveillance Station, then specify the camera each of those 4 notifications is applicable to. See the notifications heading in the readme for an example. 👍

**Comment by morgsman** [comment]
Ah I see - so I just create four Webhooks notifications in the settings file - one for each camera with the camera variable set accordingly? That's cool.

**Comment by djdd87** [comment]
> This is the version that works
> <img width="655" alt="Screen Shot 2021-05-15 at 6 27 45 pm" src="https://user-images.githubusercontent.com/75959855/118353804-511fb680-b5ab-11eb-953f-1239bfe20827.png">
> 

The version that doesn't work is what I'd like to see please 😃

**Comment by morgsman** [comment]
Yes I assumed that but I have actually changed the camera name now. The only different is the URL is

192.168.0.10:8889/Camera/Front Of House

Maybe I should have put % for the spaces

**Comment by djdd87** [comment]
%20 is what you need for the spaces because surveillance station doesn't escape the URL automatically for whatever reason. 

/Camera/Front%20Of%20House is what you need.

**Comment by morgsman** [comment]
Super helpful - thanks so much. I will give all of this a good test tomorrow and let you know if everything works as required.

**Comment by morgsman** [comment]
Do you know any way of getting a notification via Homekit by the way. I am setting it up with Telegram but ideally would like to use Homekit on my various devices.

**Comment by djdd87** [comment]
It only currently supports the types of notifications on the readme, so
unless it can be called by a generic webhook notification type, then not
currently.

You can raise a separate issue on here asking for SynoAI to support it and
I'll have a look into it for you when I get some time or someone else might
pick it up and contribute it.

**Comment by morgsman** [comment]
OK no worries - thanks. IFTTT is a possibility but not sure if the image passed through to that correctly.

**Comment by djdd87** [comment]
I had a quick look and there's an API so it's probably doable.

**Comment by morgsman** [comment]
For Homekit? I think many people would be interested in this as it would also trigger automations etc.

I can definitely trigger IFTTT with a Webhook - I use that already.

**Comment by djdd87** [comment]
Yep for homekit.

**Comment by morgsman** [comment]
that would be amazing!

**Comment by morgsman** [comment]
OK I have this working now including the Telegram notification. The only item I can't get to work is the Webhook from SynoAI to trigger Synology to record. I have this working fine with SSSAI so have the action rule already set up with the Webhook URL defined. However although the log says the Webhooks is triggered it never actually happens.

This is what my appsettings file looks like for the notifications area. Can you spot what I am doing incorrectly? I know the URL is correct as I have checked this and it is the same as per the config I have for SSSAI. Initially I thought it was the camera variable so removed that. Then I even set up a new action rule especially for this and it still didn't work. Many thanks.

  "Notifiers": [
    {
      "Type": "Telegram",
      "ChatID": "xxxx",
      "Token": "xxxx",
      "PhotoBaseURL":""
    },
    {
      "Type": "Webhook",
      "Url": "http://192.168.0.10:1967/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method=Incoming&version=1&token=YTk9MvrryWrhkj4VS7lCeIaEoH5Q573qKcxw0oIWTOxxc2fmQM5FjXwY4MW9tX8G"
    }
  ],

**Comment by djdd87** [comment]
The webhook method defaults to POST, but surveillance station needs to be GET. 

`"Method":"GET"`

**Comment by morgsman** [comment]
Thank you.

**Comment by morgsman** [comment]
Hi - I have got this all working now and it's great. Thanks again for all your efforts. I have two queries though:

1) I can't seem to change the colour of the box that is applied to the photo (I am trying to change it to  yellow). I put the following parameters in the config file:
"Boxcolour": "#FAFF00",
Initially I wondered if I should leave out the "" but if I do the container fails to load.
2) I have noticed that my AI sometimes is not detecting an object whereas with SSSAI it wasn't really a problem. Clearly there is something going on in Deepstack rather than SYNOAI. However is it possible to get further debug information in the log on what is returned from Deepstack? At the moment it simply says 'nothing detected by AI'. It would be useful to see if something was detected (e.g. a different object type) or whether it was below the defined threshold - I can then get a better idea of how to adjust my settings. Hope that makes sense. I have the feature turned on for recording the original snapshot but of course if no AI is detected then there is no after snapshot highlighting the images etc (even with the ALL parameter turned on).

**Comment by djdd87** [comment]
Hey, no worries and thanks for the coffee! :)

1. As per the readme, it's "BoxColor" (note the americanised spelling and casing), e.g. "BoxColor": "#FAFF00"
2. If you want further details about what the AI is setting, then set the logging to "Information" (or "Debug"). There's an example in the [readme](https://github.com/djdd87/SynoAI#logging).

My guess would be that it's detecting items but potentially they're too small and are getting ignored. This can be very camera dependent, so ensure you're setting an appropriate MinSizeX/MinSizeY (this can be set on both the top level config as a default and then be overridden on a camera by camera basis - again, examples in the readme).

**Comment by morgsman** [comment]
No worries for the coffee!

Can't believe I made the spelling mistake!

I already have the logging set to 'information'. Will 'debug' provide more information?
I have the min and max size set to 40 for both but maybe that's not small enough. I am using a 1080p camera rather than 4k.

**Comment by djdd87** [comment]
40 _should_ be plenty small enough. If the logs aren't showing anything and you've definitely set it to debug (maybe send me your config here so I can check it's all correct), it sounds like the AI just isn't detecting it? With information logging on, you should see lines like this:

> Camera: Car (60.509%) [Size: 100,100] [Start: 0,0, | End:100,100]"

**Comment by morgsman** [comment]
I have set it to debug now so will see what info I get. When I do get a match I can see information from deep stack as you suggest. What I am more looking for is information when my object isn’t matched to help me work out why. E.g. is it detecting a different object type etc. 

I am getting probably 80% success with matches. The problem is more at night time or in poor light. This is most likely the camera but it was detecting ok when I was using SSSAI.

**Comment by djdd87** [comment]
DeepStack themselves say that it's not the best at detecting things at night and in IR. The way my code works is to get all objects from AI, log out **all** detected objects as Information and then it filters out types you don't care about inside SynoAI later:

`private async Task<IEnumerable<AIPrediction>> GetAIPredications(Camera camera, byte[] imageBytes)
{
    _logger.LogInformation($"{camera}: Processing.");

    IEnumerable<AIPrediction> predictions = await _aiService.ProcessAsync(camera, imageBytes);
    if (predictions == null)
    {
        _logger.LogError($"{camera}: Failed to get get predictions.");
        return null;
    }
    else
    {
        foreach (AIPrediction prediction in predictions)
        {
            _logger.LogInformation($"{camera}: {prediction.Label} ({prediction.Confidence}%) [Size: {prediction.SizeX}x{prediction.SizeY}] [Start: {prediction.MinX},{prediction.MinY} | End: {prediction.MaxX},{prediction.MaxY}]");
        }
    }

    return predictions;
}`

So if there's no log after seeing "CameraName: Processing", then DeepStack didn't see anything.
