### ISSUE TITLE
synoai docker keeps failing when trigger action rule runs

### ISSUE THREAD

**Issue by mileyceberus** [djdd87/SynoAI#32]
Both synoai and deepstack dockers are running. However, every time I click "test send" on the trigger action rule on surveillance station, synoai docker stops with the following errors:

```
warn: SynoAI.Services.AIService[0]      
      Entrance: DeepStackAI: Failed to call API with HTTP status code 'Forbidden'.
fail: SynoAI.Controllers.CameraController[0]      
      SynoAI.Models.Camera: Failed to get get predictions.
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')   
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)   
   at SynoAI.Controllers.CameraController.Get(String id) in /src/Controllers/CameraController.cs:line 92   
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)   
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)   
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

My configuration is as follows:

- DS918+, 12GB RAM
- appsettings.json (cut n paste from your README except for the URI, CREDENTIAL & CAMERA_NAME)

```
{
  "AllowedHosts": "*",

  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Information",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },

  "Url": "https://dsm:5001",
  "User": "dsmuser",
  "Password": "dsmpass",
  "AllowInsecureUrl": false,

  "Delay": 5000,
  "DrawMode": "Matches",

  "AI": {
    "Type": "DeepStack",
    "Url": "http://dsm:83",
  },

  "Notifiers": [
    {
      "Type": "Telegram",
      "Token": "token",
      "ChatID": "XXX"
    }
  ],

  "Cameras": [
    {
      "Name": "Entrance",
      "Types": [ "Person" ],
      "Threshold": 50,
      "MinSizeX": 25,
      "MinSizeY": 50
    },
    {
      "Name": "Backyard",
      "Types": [ "Person", "Cat" ],
      "Threshold": 50,
      "MinSizeX": 25,
      "MinSizeY": 50
    }
  ]
}
```
Docker status:
```
root@synology:~# docker ps
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS              PORTS                                         NAMES
1e4720ca3a24        djdd87/synoai:latest           "dotnet SynoAI.dll"    31 hours ago        Up 7 seconds        0.0.0.0:8080->80/tcp, 0.0.0.0:8443->443/tcp   synoai
73fb8c321365        deepquestai/deepstack:latest   "/app/server/server"   31 hours ago        Up About an hour    0.0.0.0:83->5000/tcp                          deepstack

```

**Comment by djdd87** [comment]
What do you see if you go to http://dsm:83? Add a screenshot.

Also, I just committed a fix for "Unhandled exception. System.ArgumentNullException: Value cannot be null". That won't fix your issue, but it will prevent the bolded part of the logs:

warn: SynoAI.Services.AIService[0]      
      Entrance: DeepStackAI: Failed to call API with HTTP status code 'Forbidden'.
fail: SynoAI.Controllers.CameraController[0]      
      SynoAI.Models.Camera: Failed to get get predictions.
**Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')   
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)   at 
...
TState& state)   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()**

**Comment by mileyceberus** [comment]
Deepstack activated screenshot attached. 

<img width="590" alt="Screen Shot 2021-05-27 at 10 43 46 pm" src="https://user-images.githubusercontent.com/84911442/119827986-16b80100-bf3d-11eb-98f2-683cba545d1f.png">

**Comment by mileyceberus** [comment]
<img width="1361" alt="Screen Shot 2021-05-27 at 11 11 37 pm" src="https://user-images.githubusercontent.com/84911442/119832062-32250b00-bf41-11eb-9d96-20f9c1b8ff16.png">

**Comment by djdd87** [comment]
Remove the colon after VISION-DETECTION. If VISION-DETECTION isn't enabled, then it won't work.

Should be:

> "VISION-DETECTION=True",

**Comment by mileyceberus** [comment]
Oops, fat fingers. Removing the extra colon fixed it. Thanks.
