### ISSUE TITLE
Rotate capture

### ISSUE THREAD

**Issue by JohannCR** [djdd87/SynoAI#36]
I have cameras that don't support rotation, hence surveillance station's rotate option is greyed out.
Problem is, the field I want to capture is high and narrow, so I have to use the camera rotated 90° and even though mouvement detection is not impacted, unsurprisingly deepstack doesn't seem to recognize objects...
Is it doable to rotate the capture before sending to deepstack ? How could it be done ?

**Comment by djdd87** [comment]
This should be [relatively easy to implement](https://stackoverflow.com/a/45100816) using the SKSharp image library I already use for image handling. 

The only thing to bear in mind is that users who have set SaveOriginalSnapshot=true will probably also want the original image rotated as well.

The setting should be added on a camera by camera basis, probably as a config like:
``` json
{
  "Name": "BackDoor",
  "Types": [ "Person" ],
  "Rotate": -90,
}```

**Comment by JohannCR** [comment]
Nice thanks. Can't wait
(but I will ^^)
