### ISSUE TITLE
Object detection failing

### ISSUE THREAD

**Issue by JohannCR** [djdd87/SynoAI#37]
Hi,
I have a weird case of object detection that is not working as intended. Here are two contrasting examples :

-  Example 1. Everything works fine on one camera, set to detect "person" type objects at 65% confidence min (needs this high because I got some weird looking tree in human shape I guess^^). Detection is fairly reliable, very happy with the results.

- Example 2. On another camera though it's not. It's an indoor camera that obviously sees a lot of objects : chairs, potted plants, dining table, vase, plant, cup... it's actually quite impressive that it detects all of that. But I set it to detect "cat" (this is the target) and  "person" (just to test it out) at 40% threshold (not too demanding for now). No particular option added to config (no xmin/ymin neither), just:
`{
      "Name": "Entree",
      "Types": ["cat", "person"],
      "Threshold": 40,
      "DrawMode": "off"
    }`
It has NEVER detected any of my two cats. 
Sometimes it detects a person, but fails to recognize it as a success:
`SynoAI.Models.Camera: person (59.8814400%) [Size: 56x364] [Start: 464,307 | End: 520,671]`
followed by
`Entree: Nothing detected by the AI exceeding the defined confidence level and/or minimum size`
Uhhhh yes it did, it just said 59% on a person ! It does exceed confidence level... What's up with that ?
Sometimes it does not even detect persons (no mention in the log)...

I'm thinking there are too many objects, so deepstack does a few and drops the rest maybe ?

Any idea ?

**Comment by djdd87** [comment]
Hi, it doesn't sound like a deepstack issue around the number of objects, no, because it's correctly identifying the person with a confidence exceeding your defined threshold. From the logs you've provided that should be alerting you.

Please provide your config and I'll have a look.

**Comment by djdd87** [comment]
This [post](https://forum.deepstack.cc/t/didnt-detect-the-cat/497) implies DeepStack struggles to differentiate between dogs and cats, so for that issue you could try specifying dog as well as cat and see if you have more luck.

**Comment by JohannCR** [comment]
Here's the full (redacted^^) config. Do you need anything else ?

`{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },
  "Url": "http://172.17.0.1:1020",
  "User": "xxxxxxxxxxx",
  "Password": "xxxxxxxxxxx",
  "AI": {
    "Type": "DeepStack",
    "Url": "http://172.17.0.1:83"
  },
  "Notifiers": [
    {
      "Type": "Webhook",
      "Url": "http://192.168.68.116:8123/api/webhook/xx",
      "Cameras": ["Jardin"]
    },
    {
    	"Type": "Webhook",
    	"Url": "http://172.17.0.1:1020/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method=Incoming&version=1&token=QdOhIvejSMOpz3pCDNIQ8hqN3vNcsKPdPk9kcqv875RFjZ8CSUvZR4166oVsrJPU",
    	"Method":"GET",
    	"Cameras": ["Jardin"]
    },
    {
    	"Type": "Webhook",
    	"Url": "https://xxxxxxx.synology.me:4745/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method=Incoming&version=1&token=RKLp6bLzsDa2wcuF93ggVbNZOjXEm7GdO83I1IjuMXqOqMRhl5l4jIE81LVoIuII",
    	"Method":"GET",
    	"Cameras": ["Entree"]
    },
    {
		"Type": "Email",
		"Destination": "xxxxxxxxxx@gmail.com",
		"Host": "smtp.gmail.com",
		"Port": 587,
		"Encryption": "StartTLS",
		"Username": "xxxxxxxxxx@gmail.com",
		"Password": "xxxxxxxxxxxx",
		"Cameras": ["Jardin", "Entree"]
	}
  ],
  "Cameras": [
    {
      "Name": "Jardin",
      "Types": ["person"],
      "Threshold": 65,
      "DrawMode": "off"
    },
    {
      "Name": "Entree",
      "Types": ["cat", "person"],
      "Threshold": 40,
      "DrawMode": "off"
    }
  ]
}
`

**Comment by djdd87** [comment]
Can you send me the full log please. Stick it on pastebin and provide a link.

**Comment by JohannCR** [comment]
https://pastebin.com/SJTarimY

**Comment by djdd87** [comment]
I don't see any mention of "Person" in those logs, but what I have noticed that'll make this hard to diagnose is that the logging should be not be showing:
> SynoAI.Models.Camera: person (59.8814400%) [Size: 56x364] [Start: 464,307 | End: 520,671]

But should be:
> {CAMERA NAME}: person (59.8814400%) [Size: 56x364] [Start: 464,307 | End: 520,671]

Where {CAMERA NAME} would be Jardin/Entree. I've just committed a fix for that. My suspicion on your person detection is that it's actually the other camera detecting it, but as it's not showing the actual camera name it's not obvious.

Wait 30 minutes, pull the latest docker image and try again... maybe go and jump up and down in front of the Entree camera and see what happens, then report back with the logs if it's still not detecting you.

**Comment by JohannCR** [comment]
Well before pulling the latest docker image, I added "dog" and after two restarts it started to detect persons...
Pulled the latest and I don't see any difference in the log (except for the person, yeeaah!)

info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
info: SynoAI.Controllers.CameraController[0]
      Entree: Motion detected, fetching snapshot.
info: SynoAI.Services.SynologyService[0]
      Entree: Taking snapshot
info: SynoAI.Controllers.CameraController[0]
      Entree: Snapshot received (217ms).
info: SynoAI.Controllers.CameraController[0]
      SynoAI.Models.Camera: Processing.
info: SynoAI.Services.AIService[0]
      Entree: DeepStackAI: Processed successfully (2320ms).
info: SynoAI.Controllers.CameraController[0]
      SynoAI.Models.Camera: chair (47.0311500%) [Size: 513x622] [Start: 577,663 | End: 1090,1285]
info: SynoAI.Controllers.CameraController[0]
      SynoAI.Models.Camera: chair (53.30134600%) [Size: 131x195] [Start: 2173,653 | End: 2304,848]
info: SynoAI.Controllers.CameraController[0]
      SynoAI.Models.Camera: dining table (54.97862700%) [Size: 1055x397] [Start: 1173,734 | End: 2228,1131]
info: SynoAI.Controllers.CameraController[0]
      SynoAI.Models.Camera: chair (56.7922100%) [Size: 428x307] [Start: 659,984 | End: 1087,1291]
info: SynoAI.Controllers.CameraController[0]
      SynoAI.Models.Camera: potted plant (66.7427900%) [Size: 168x258] [Start: 202,393 | End: 370,651]
info: SynoAI.Controllers.CameraController[0]
      SynoAI.Models.Camera: potted plant (71.0321500%) [Size: 244x264] [Start: 1300,506 | End: 1544,770]
info: SynoAI.Controllers.CameraController[0]
      SynoAI.Models.Camera: potted plant (71.36611300%) [Size: 260x208] [Start: 1641,554 | End: 1901,762]
info: SynoAI.Controllers.CameraController[0]
      SynoAI.Models.Camera: chair (79.79651700%) [Size: 532x457] [Start: 1772,833 | End: 2304,1290]
info: SynoAI.Controllers.CameraController[0]
      SynoAI.Models.Camera: chair (85.2831300%) [Size: 641x321] [Start: 1069,966 | End: 1710,1287]
info: SynoAI.Controllers.CameraController[0]
      SynoAI.Models.Camera: person (86.7655200%) [Size: 186x502] [Start: 1548,203 | End: 1734,705]
info: SynoAI.Controllers.CameraController[0]
      SynoAI.Models.Camera: chair (86.8241200%) [Size: 298x189] [Start: 1881,647 | End: 2179,836]
info: SynoAI.Controllers.CameraController[0]
      Entree: Webhook: Processing
info: SynoAI.Controllers.CameraController[0]
      Entree: Webhook: Calling GET.
info: SynoAI.Services.ISnapshotManager[0]
      Entree: Processing image boundaries.
info: SynoAI.Services.ISnapshotManager[0]
      Entree: Finished processing image boundaries (97ms).
info: SynoAI.Services.ISnapshotManager[0]
      SynoAI.Models.Camera: Saving image to 'Captures/Entree/Entree_2021_06_16_19_23_35_233.jpeg'.
info: SynoAI.Services.ISnapshotManager[0]
      SynoAI.Models.Camera: Imaged saved to 'Captures/Entree/Entree_2021_06_16_19_23_35_233.jpeg' (137ms).
info: SynoAI.Controllers.CameraController[0]
      Entree: Webhook: Success.
info: SynoAI.Controllers.CameraController[0]
      Entree: Email notification sent successfully
info: SynoAI.Controllers.CameraController[0]
      Entree: Notifications sent (3125ms).
info: SynoAI.Controllers.CameraController[0]
      Entree: Finished (5682ms).

Cannot find any of my cats to test out yet lol but I will report back as soon as I do

**Comment by djdd87** [comment]
I've pulled the latest image down and the logs are working fine. Make sure you follow the instructions on the [readme](https://github.com/djdd87/SynoAI#updating) when updating.

If the object types are prefixed with "SynoAI.Models.Camera" then you're not on the latest version. You should see something like:
>      Driveway: car (67.40587400%) [Size: 258x492] [Start: 2046,514 | End: 2304,1006]

Unfortunatley if you're not seeing objects which are in the image when it's captured, then you're going to have to take this up with DeepStack as I can only act on the detected types. I'd suggest turning on SaveOriginalSnapshot, find the image that wasn't detected and use that in your error report to them.

**Comment by JohannCR** [comment]
Yes ! Got one instance of cat (dog) detection. We're good now.
You were right about the latest image, I got it now and the camera name shows up in the log. Useful^^
Thanks for your help !

**Comment by djdd87** [comment]
No worries!
