### ISSUE TITLE
Detection only works on one camera since #36

### ISSUE THREAD

**Issue by JohannCR** [djdd87/SynoAI#40]
Hi,

I implemented the "Rotate" option on one of my cameras, and the others do not work anymore...
Action rule fires on all of them, but I see only the rotated camera sending a capture to deepstack. Keeps happening even when I remove the rotate option.

**Comment by JohannCR** [comment]
Same thing with stable version. Are they identical ? Otherwise could it be my setup as I'm on degraded mode waiting for a replacement HDD ? I don't see why but asking anyway^^

**Comment by djdd87** [comment]
It works fine for me. Please provide your config.

The stable build is 6 months old and I don't keep it updated. I need to remove it and go to a proper versioning system.

**Comment by djdd87** [comment]
@JohannCR ?

**Comment by JohannCR** [comment]
Sorry for the delay, had too much work these last few days ^^

Here is my config. The only changes since it worked were the "rotate" part, "information" log and "saveoriginalsnapshot" to true.

> {
>   "Logging": {
>     "LogLevel": {
>       "Default": "Information",
>       "Microsoft": "Warning",
>       "Microsoft.Hosting.Lifetime": "Information"
>     }
>   },
>   "Url": "http://172.17.0.1:1020",
>   "User": "xxxxxxxxx",
>   "Password": "xxxxxxxxxx",
>   "SaveOriginalSnapshot": true,
>   "AI": {
>     "Type": "DeepStack",
>     "Url": "http://172.17.0.1:83"
>   },
>   "Notifiers": [
>   	{
> 	  "Type": "Pushbullet",
> 	  "ApiKey": "xxxxxxxxxxxxxxxx"
> 	},
>     {
>       "Type": "Webhook",
>       "Url": "http://192.168.68.116:8123/api/webhook/mouvement_jardin",
>       "Cameras": ["Jardin", "JardinEst"]
>     },
>     {
>     	"Type": "Webhook",
>     	"Url": "http://172.17.0.1:1020/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method=Incoming&version=1&token=xxxxxxxxx",
>     	"Method":"GET",
>     	"Cameras": ["Jardin"]
>     },
>     {
>     	"Type": "Webhook",
>     	"Url": "http://172.17.0.1:1020/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method=Incoming&version=1&token=xxxxxxxxxx",
>     	"Method":"GET",
>     	"Cameras": ["JardinEst"]
>     },
>     {
>     	"Type": "Webhook",
>     	"Url": "http://172.17.0.1:1020/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method=Incoming&version=1&token=xxxxxxxxxxx",
>     	"Method":"GET",
>     	"Cameras": ["Entree"]
>     }
>     //{
> 	//	"Type": "Email",
> 	//	"Destination": "xxxxxxxxxxxxxxxxxxx",
> 	//	"Host": "smtp.gmail.com",
> 	//	"Port": 587,
> 	//	"Encryption": "StartTLS",
> 	//	"Username": "xxxxxxxxxxxxxxx",
> 	//	"Password": "xxxxxxxxxxxxxxx",
> 	//	"Cameras": ["Entree", "Jardin", "JardinEst"]
> 	//}
>   ],
>   "Cameras": [
>     {
>       "Name": "Jardin",
>       "Types": ["person"],
>       "Threshold": 65,
>       "DrawMode": "off"
>     },
>     {
>       "Name": "JardinEst",
>       "Types": ["person"],
>       "Threshold": 60,
>       "DrawMode": "off",
>       "Rotate": 90
>     },
>     {
>       "Name": "Entree",
>       "Types": ["person"],
>       "Threshold": 60,
>       "DrawMode": "off"
>     },
>   ]
> }
> 

Here is the initalization log showing that the config is processed without error :

> 2021-07-20 07:05:30	stdout	      Content root path: /app
> 2021-07-20 07:05:30	stdout	[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
> 2021-07-20 07:05:30	stdout	      Hosting environment: Production
> 2021-07-20 07:05:30	stdout	[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
> 2021-07-20 07:05:30	stdout	      Application started. Press Ctrl+C to shut down.
> 2021-07-20 07:05:30	stdout	[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
> 2021-07-20 07:05:30	stdout	      Now listening on: http://[::]:80
> 2021-07-20 07:05:30	stdout	[40m[32minfo[39m[22m[49m: Microsoft.Hosting.Lifetime[0]
> 2021-07-20 07:05:29	stdout	      Initialisation successful.
> 2021-07-20 07:05:29	stdout	[40m[32minfo[39m[22m[49m: SynoAI.Services.SynologyService[0]
> 2021-07-20 07:05:29	stdout	      GetCameras: Successful. Found 3 cameras.
> 2021-07-20 07:05:29	stdout	[40m[32minfo[39m[22m[49m: SynoAI.Services.SynologyService[0]
> 2021-07-20 07:05:29	stdout	      GetCameras: Fetching Cameras
> 2021-07-20 07:05:29	stdout	[40m[32minfo[39m[22m[49m: SynoAI.Services.SynologyService[0]
> 2021-07-20 07:05:29	stdout	      Login: Successful
> 2021-07-20 07:05:29	stdout	[40m[32minfo[39m[22m[49m: SynoAI.Services.SynologyService[0]
> 2021-07-20 07:05:28	stdout	      Login: Authenticating
> 2021-07-20 07:05:28	stdout	[40m[32minfo[39m[22m[49m: SynoAI.Services.SynologyService[0]
> 2021-07-20 07:05:28	stdout	      API: Successfully mapped all end points
> 2021-07-20 07:05:28	stdout	[40m[32minfo[39m[22m[49m: SynoAI.Services.SynologyService[0]
> 2021-07-20 07:05:26	stdout	      API: Querying end points
> 2021-07-20 07:05:26	stdout	[40m[32minfo[39m[22m[49m: SynoAI.Services.SynologyService[0]
> 2021-07-20 07:05:26	stdout	      Initialising
> 2021-07-20 07:05:26	stdout	[40m[32minfo[39m[22m[49m: SynoAI.Services.SynologyService[0]
> 2021-07-20 07:05:25	stdout	      Processing Webhook Config
> 2021-07-20 07:05:25	stdout	[40m[32minfo[39m[22m[49m: SynoAI.Startup[0]
> 2021-07-20 07:05:25	stdout	      Processing Webhook Config
> 2021-07-20 07:05:25	stdout	[40m[32minfo[39m[22m[49m: SynoAI.Startup[0]
> 2021-07-20 07:05:25	stdout	      Processing Webhook Config
> 2021-07-20 07:05:25	stdout	[40m[32minfo[39m[22m[49m: SynoAI.Startup[0]
> 2021-07-20 07:05:25	stdout	      Processing Webhook Config
> 2021-07-20 07:05:25	stdout	[40m[32minfo[39m[22m[49m: SynoAI.Startup[0]
> 2021-07-20 07:05:25	stdout	      Processing Pushbullet Config
> 2021-07-20 07:05:25	stdout	[40m[32minfo[39m[22m[49m: SynoAI.Startup[0]
> 2021-07-20 07:05:25	stdout	      Processing notifier config.
> 2021-07-20 07:05:25	stdout	[40m[32minfo[39m[22m[49m: SynoAI.Startup[0]
> 2021-07-20 07:05:25	stdout	      Processing camera config.
> 2021-07-20 07:05:25	stdout	[40m[32minfo[39m[22m[49m: SynoAI.Startup[0]
> 2021-07-20 07:05:25	stdout	      Processing config.
> 2021-07-20 07:05:25	stdout	[?1h=[40m[32minfo[39m[22m[49m: SynoAI.Startup[0]


After that, I only have log entries for the one camera where I put "rotate". None of the other show up (it's been 2 days now).
SSS action rules have not been changed either, and the history show that the ones that trigger synoAI correctly all launch (for every camera).
![image](https://user-images.githubusercontent.com/7448079/126607763-77c6e9c8-b3bb-4e6e-b19d-4523074beec9.png)

Plus I also systematically start recording when synoAI is triggered, whether or not it detects any object, so I know the rules fire.

The rules that initiate recording when an object is detected by synoAI (I know they are useless because of the last statement but I keep them for now to see when synoAI fired the webhooks) though do not launch anymore indicating that synoAI has not used any of the webhooks.

I'm kind of baffled by what's wrong in my config. Cannot find my mistake though there must be one, no ?
Thanks for your help

**Comment by djdd87** [comment]
What happens if you make the call directly for a camera without rotation?

http[s]://NAS:PORT/Camera/Entree

Do you get logs then?

**Comment by JohannCR** [comment]
Damn ! I just hit the "try" button in the sss rule and it showed up in the logs... So that means it's a bug with surveillance station ?

**Comment by djdd87** [comment]
Have you recently updated? I had someone had a similar issue message me on Reddit:

![image](https://user-images.githubusercontent.com/22151993/126611068-5f2d6d6d-17ff-4bb1-a3fe-bae75c6eabbc.png)

**Comment by JohannCR** [comment]
omg that worked ! weird bug... Thank you so much
