### ISSUE TITLE
Docker closing very fast after startup

### ISSUE THREAD

**Issue by Argosy87** [djdd87/SynoAI#44]
Hi,

My docker is closing very quickly after starting...
Log file: https://pastebin.com/biVFrQzj
appsettings.json file : https://pastebin.com/DzRa5Cmf

**Comment by djdd87** [comment]
It's timing out trying to reach your Synology instance. Could be an incorrect IP/subnet/firewall issue. 

Unfortunately this is unlikely to be a SynoAI issue.

**Comment by Argosy87** [comment]
I can reach my synology from my webbrowser and login with the user specified in the appsettings.
Do you know if everything still works with DSM 7?

**Comment by djdd87** [comment]
A number of people are using it without issue. What network settings did you use for your docker container?

**Comment by Argosy87** [comment]
bridge 8080:80 4443:443

**Comment by djdd87** [comment]
What do you get if you go to the following URL?

http://YOUR-IP:5000/webapi/query.cgi?api=SYNO.API.Info&version=1&method=query

**Comment by Argosy87** [comment]
Now that i made connection available trough the internet it seems to work?
Why does it need the outside connection possible?

**Comment by djdd87** [comment]
It shouldn't do? Can you send me a screenshot of what you've set?

**Comment by Argosy87** [comment]
Ok, it is a firewall issue like you sayd the first post, because of the bridge setting in network settings.
I have a rule in the firewall to allow access to everything in my network but nothing else outside this range.
Bridge network docker client makes another network range so had to include this to in my firewall settings :-)
