### ISSUE TITLE
Camera ID on webhook

### ISSUE THREAD

**Issue by EzequielPitton78** [djdd87/SynoAI#46]
Hello! Is it a way to pass the camera id in the webhook notifier? I have some logic in node red to treat the detections depending on the status of the alarm and for occupation calculation.   

I have created separate notifiers for each camera but having 36 of them I wonder if it's a better way :)

Ezequiel

**Comment by djdd87** [comment]
Not at the moment, but I was planning on some point of adding the ability to define a template for the webhook data, so we could do something like:
```json
{
   "Id": "{{ID}}",
}
```
Someone asked for NodeRed support in #13. Do you have any documentation on how it works and what format of data it expects?

**Comment by EzequielPitton78** [comment]
Hello! i would say you only need to make sure the web hook is posting Content-Type : application/json and that would be enough to be read by node red

**Comment by p-u-a** [comment]
> Hello! i would say you only need to make sure the web hook is posting Content-Type : application/json and that would be enough to be read by node red

Yeah this would be really cool, you could do so much with it then.

**Comment by gabrielpc1190** [comment]
You already have this information on the logging, so you can just add it to the data object you're sending!

**Comment by djdd87** [comment]
> You already have this information on the logging, so you can just add it to the data object you're sending!

It's not that easy as I want to eventually have configurable templates as mentioned above. But if you think it is, I'm always open to pull requests.

**Comment by gabrielpc1190** [comment]
Dear @djdd87 

Why not adding it just in the mean time you have time to do the more complex thing you want?

I'm trying to automate my alarm based on which camera it's activated. That extra field of information will solve a lot for many of us! If not, I'll have to use n8n and create a workflow to do it, possible, but includes a third program in the flow that may cause problems.
I can buy you a coffee for your time!

**Comment by gabrielpc1190** [comment]
For anyone else looking for this functionality to work on Home Assistant:
I just found out that the push camera integration receives from the webhook an attribute called filename, on it there is the camera name. Parsing the filename you can know which camera was activated!
![image](https://user-images.githubusercontent.com/6482688/150847762-5ee2058e-e89d-45c5-8086-9f36d0837b7a.png)


I'm going to try this, since I'm not a programmer and can't make a fork and write the code myself.

I'm really loving this app. Thanks a lot to @djdd87 and the others contributing to it!

**Comment by djdd87** [comment]
You can also just create a separate webhook per camera in HA and setup a notifier for each camera in SynoAI.

**Comment by gabrielpc1190** [comment]
That would be great!
How to create a notifier for only one camera instead of all?

**Comment by djdd87** [comment]
https://github.com/djdd87/SynoAI#notifications

**Comment by gabrielpc1190** [comment]
Thank you man. I didn't understand that for each notifier (every individual
webhook) I can have different cameras instead of all.
Really appreciate it.
Just bough a coffee for you!

**Comment by djdd87** [comment]
Changed the image inclusion (multipart/form-data) to include the form values:

![image](https://user-images.githubusercontent.com/22151993/151721249-048bab10-34fb-41d8-9eec-75ca52b2d10e.png)

When SendImage is false, the request will be made using application application/json:

![image](https://user-images.githubusercontent.com/22151993/151721270-f39f8585-7484-4605-bd8f-73f4e68b34b2.png)

**Comment by djdd87** [comment]
Added in release ```latest``` or ```v1.1.2```.
