### ISSUE TITLE
Capture folder only contains processed image if invoked notifier method needs it

### ISSUE THREAD

**Issue by Ewarren7** [djdd87/SynoAI#49]
Hey awesome project. This is so useful, especially dockerized. My thanks to you and Christopher Adams.

I wanted to mention a quirk I didn't see documented. 

Image captures only save processed images to the captures folder if one of the notifiers that is being used utilizes the image. ie if use pushbullet, email with image, or a webhook post with image... notifier then the image ultimately gets saved. Otherwise it actually doesn't ever invoke the method to save it. 

In my case, I wanted to switch from push bullet to webhook get request only as the notifier (targeting homebridge webhooks switch that triggers [homebridge-camera-ffmpeg](https://github.com/Sunoo/homebridge-camera-ffmpeg) motion detector for the camera so I get a native homekit ios alert) and the processed images were not saving as that notifier type doesn't need the image but I still wanted them saved

To solve for me I just added a GET case to the webhook notifier [here](https://github.com/djdd87/SynoAI/blob/03601a05eacc636c255078c6347dca9b70bd4397/SynoAI/Notifiers/Webhook/Webhook.cs#L82) and have it save the image
```
  switch (Method)
                {
                    case "PATCH":
                    case "POST":
                    case "PUT":
                        if (SendImage)
                        {
                            ProcessedImage processedImage = snapshotManager.GetImage(camera);
                            fileStream = processedImage.GetReadonlyStream();
                            data.Add(new StreamContent(fileStream), Field, processedImage.FileName);
                        }
                        break;      
                    case "GET":
                       snapshotManager.GetImage(camera);
                       break;                      
                }                
```

Perhaps it would be desirable to always save the image on a match regardless of the notifiers used?

**Comment by djdd87** [comment]
This is now always saved when there's a match by @euquiq 's changes.
