### ISSUE TITLE
Camera Name with Space fails to Trigger Rule

### ISSUE THREAD

**Issue by AdiAbuAli** [djdd87/SynoAI#51]
Hi,
I have a camera with space in it's name (Back Door)....I can't create a rule with webhook with URL with space, such as :

http://10.0.0.15:8080/Camera/Back Door

I tried to use the following:
http://10.0.0.15:8080/Camera/Back_Door

and define it in the setting file as Back_Door, but attached error caused the applicatioon to shutdown....

![Capture](https://user-images.githubusercontent.com/89463853/132144474-bdfce390-0666-46f3-93f0-f885b8cd35b0.JPG)

**Comment by djdd87** [comment]
Use %20 instead of a blank space.

http://10.0.0.15:8080/Camera/Back%20Door

**Comment by AdiAbuAli** [comment]
Thanks for the prompt response....
Same %20 to be inserted in Camera name in setting.json file, or there I can put a space normally?

Thanks,
________________________________

**Comment by djdd87** [comment]
No, you don't need to change anything in your settings file. The fault is in DSM as Synology isn't encoding the URL properly, which is why you need to manually add the %20 symbol to represent the space.

**Comment by AdiAbuAli** [comment]
Thank you...it works now!

Thanks,
________________________________
