### ISSUE TITLE
Test development branch

### ISSUE THREAD

**Issue by lucasCFO** [djdd87/SynoAI#54]
Hi,

I'm really curious to test what's on the development branch, but I don't know how to proceed...

Would it be possible to add the ability on docker to choose between latest or development when downloading the synoai image?

Thanks

**Comment by djdd87** [comment]
At the moment you'll need to compile the image yourself and then add it manually to DSM. Docker Hub have changed their licensing recently, so I can no longer do automatic builds without paying for it.

**Comment by euquiq** [comment]
I don't know if I'm "trespassing" somehow the "netiquette" with this, so please tell me @djdd87 and I can delete this text. Having said that, if you search in docker for "euquiq" on their registry, I got the development image compiled in there. If you download it into your Synology, you can have both Syonai "main" and that new "development" inside your Synology, but you can only turn one  of them at a time.

The "development" container needs the same installation / configuration process as the "main" one: I.E:

Edit the advanced settings
Enable auto restarts
On the volumes tab;
Add a file mapping from your appsettings.json to /app/appsettings.json
Add a folder mapping from your captures directory to /app/Captures (optional)
On the port settings tab;
Enter a port mapping to port 80 from an available port on your NAS, e.g. 8080
On the environment tab;
To change the timezone to your local time, add a variable called TZ and set the value to your locale.

etc.

**Comment by djdd87** [comment]
No that's perfectly OK @euquiq - I'll push my own image in the near future once I progress the development branch to main.

**Comment by lucasCFO** [comment]
That's perfect @euquiq!
Thank you for your work guys! ;-)
