### ISSUE TITLE
Cannot connect to syno API when the password contains "+"

### ISSUE THREAD

**Issue by JohannCR** [djdd87/SynoAI#56]
Hi,

I've just updated DSM and the synoai container crashes with this error:
Login: Failed due to Synology API error code '400'

Checking the API doc it happens when the account does not exist or the password is wrong.
Problem is I can connect to DSM/sss fine with those logins...
I deactivated 2FA for this user + no account protection.
I remember having a hard time setting the user at first install due to a bug in DSM password setting, but I don't remember how I got it to work... Tried to change passwords both on DSM and sss sides, to no avail.
Any thought on this ?
Thanks

**Comment by djdd87** [comment]
![image](https://user-images.githubusercontent.com/22151993/133591246-77157da0-a53a-4ea4-8347-b26919e2589a.png)
Have you tried the advice in the FAQ?

**Comment by JohannCR** [comment]
Also tried this, but same result. thanks

**Comment by djdd87** [comment]
Sorry then, I'm afraid I can't help. I know a few people are using it on DSM 7 without issue, so it's going to be a problem with your setup.

**Comment by djdd87** [comment]
The only thing to try is to make the calls directly and see if there's any other info.

This will give you the info of the SYNO.API.Auth:

http://{NAS}:5000/webapi/query.cgi?api=SYNO.API.Info&version=1&method=query

It should look like this: 

{"SYNO.API.Auth":{"maxVersion":6,"minVersion":1,"path":"auth.cgi"}

This will perform the login action, which I'm assuming is where your error 400 is coming from:

http://{NAS}:5000/webapi/auth.cgi?api=SYNO.API.Auth&method=Login&version=6&account={USERNAME}&passwd={PASSWORD}&session=SurveillanceStation

**Comment by JohannCR** [comment]
I got
"SYNO.API.Auth":{"maxVersion":7,"minVersion":1,"path":"entry.cgi"}

and the login action sends
{"error":{"code":400},"success":false}

Note that I tried multiple user accounts, even the admin one, same result.

**Comment by djdd87** [comment]
Can you try:

http://{NAS}:5000/webapi/entry.cgi?api=SYNO.API.Auth&method=Login&version=7&account={USERNAME}&passwd={PASSWORD}&session=SurveillanceStation

**Comment by JohannCR** [comment]
version=7 gives a code 103 whether I use auth or entry

**Comment by JohannCR** [comment]
Is there a need for quotes in the password parameter ? My passwords contain special chars... I'm going to try one without any

**Comment by djdd87** [comment]
No need for quotes, no. The quotes would be considering part of the password if you add them, e.g. "password" does not equal password.

**Comment by JohannCR** [comment]
Noted. Anyway I tried both in every case. Any idea what it means ?

**Comment by djdd87** [comment]
Well, I was hoping using version 7 would fix it. See issue #5 .

You can try setting your config value for "ApiVersionInfo" to 7 and see if that helps you get further with SynoAI?

**Comment by euquiq** [comment]
When I installed SynoAI on my DSM7 I recall I had to create the user for it from inside Synology Surveillance Station Client on my computer (and not from DSM interface)

<img width="814" alt="Captura de Pantalla 2021-09-17 a la(s) 02 09 54" src="https://user-images.githubusercontent.com/31453004/133727910-a3c9ac64-b47f-4cee-979f-640c51cbf64a.png">

**Comment by JohannCR** [comment]
Got it !
Thanks @euquiq I already tried creating a user in sss and it still didn't work...

Seeing that it works for others and that we ran down every possibility, I must have made an error somewhere.
Retried every API call with lots of variants, here is what I found out:
1°) My mistake when I tested with an admin account since it had 2FA enabled it couldn't work^^
2°) Got it working by changing ONE char in my password : removed a "+"

Apparently the API call doesn't like it... I don't know if it's common knowledge or something weird here, but don't use a "+" symbol in your password ! Maybe add that to the wiki^^

PS : API calls still fail with version=7

Thanks a lot for your help !

**Comment by djdd87** [comment]
That's good to know, thanks @JohannCR. I'm suprised that it's now allowed. I suspect DSM must be splitting the querystring on the plus symbol for some reason... maybe? Their encoding handling from the action rule is pretty bad as well as they don't even encoded a blank space to %20.

Please could you try logging in again with your password with the + symbol in it and change it to %2B?

i.e. if your password is "bob+dave" then it should become "bob%2Bdave"

If that works, then I can force the encoding on that symbol. It's odd thought that it's only the + that fails as I have many special chars in my passwords and they work fine.

**Comment by JohannCR** [comment]
Sure.
It works with the encoded + as %2B in the API call. Do you want me to test it out in synoAI also ?

**Comment by djdd87** [comment]
Yeah if you could that'd be great!

**Comment by JohannCR** [comment]
Oh sorry, I edited my previous message, you probably didn't see it. Or did I misunderstand what you wanted me to test ?
Tell me if you need anything else, I'll gladly help however I can

**Comment by djdd87** [comment]
So you did! I just saw the email from GitHub and didn't see the edit. 

In which case, I can force encoding on the password as a fix for this issue.

**Comment by djdd87** [comment]
Can be fixed on the SynoAI side, shouldn't be closed.
