### ISSUE TITLE
Quality profile on sss

### ISSUE THREAD

**Issue by JohannCR** [djdd87/SynoAI#57]
Is it possible to specify a quality profile for surveillance station recording rule action ?
Cannot find a way in SSS surprisingly, maybe the webhook can force it ?

**Comment by eRJe79** [comment]
You can set the Action Rule Recoding quality statically Under IP Camera > Recording Settings > Advanced > Other Recording Settings.

If you want to change this dynamically, I don't think this is possible.

**Comment by JohannCR** [comment]
Right, thanks !
