### ISSUE TITLE
App hang when fails to fetch a snapshot

### ISSUE THREAD

**Issue by AdiAbuAli** [djdd87/SynoAI#58]
Hi,
As per attached, the app hang and restart when fails in one incident to fetch snapshot.
I think it should ignore and continue....isn't it?
![Screenshot_20211012-045849_Samsung Internet](https://user-images.githubusercontent.com/89463853/136878577-b2fcef99-a38a-42cf-af05-59f113f3db69.jpg)

**Comment by djdd87** [comment]
Hey, it shouldn't really be failing at all. Can you please provide the full log and not a truncated screenshot?

**Comment by djdd87** [comment]
Can't repro, not enough information given.
