### ISSUE TITLE
Docker Container not Running (DSM7) DS218+

### ISSUE THREAD

**Issue by Neocramencer** [djdd87/SynoAI#59]
Hi,

i tried to implement your container but it is not starting on my DS218+. Log shows the following informations:

2021-11-07 11:49:48 | stdout | Could not execute because the application was not found or a compatible .NET SDK is not installed.
-- | -- | --
2021-11-07 11:49:45 | stdout | https://aka.ms/dotnet-download
2021-11-07 11:49:45 | stdout | Install a .NET SDK from:
2021-11-07 11:49:45 | stdout | It was not possible to find any installed .NET SDKs.
2021-11-07 11:49:45 | stdout | * You intended to execute a .NET SDK command:
2021-11-07 11:49:45 | stdout | The application 'SynoAI.dll' does not exist.

Anything that iam missing?

Thanks for your Help

marc

**Comment by djdd87** [comment]
Did you get the image from the repository? Or did you try and build it with the docker file?

**Comment by Neocramencer** [comment]
Directly from the Synology Docker -> registration -> which should be the docker hub.

**Comment by djdd87** [comment]
I'm unsure then! It's working fine here and for many. At some point I need to rebuild the image and manually upload it (unfortunately DockerHub now charges for auto build functionality from GitHub repos). If you are able, you can do that yourself.

**Comment by Neocramencer** [comment]
:( well i just follwed the Manual. Is there a short manual how to build the docker image myself? i can try that an see if this helps?

**Comment by Neocramencer** [comment]
in my opinion something is wrong with the image on dockerhub...

**Comment by djdd87** [comment]
> :( well i just follwed the Manual. Is there a short manual how to build the docker image myself? i can try that an see if this helps?

I've just repushed the image. Can you give it a try?

**Comment by djdd87** [comment]
I've completely removed my SynoAI install and reinstalled it from scratch and it's all working fine for me.

**Comment by Neocramencer** [comment]
Same issue :(

Removed everything and redownloaded image. What synology do you use. Is it related to the Hardware?

best regards
Marc

**Comment by Neocramencer** [comment]
Iam using DSM: DSM 7.0.1-42218
DS218+

**Comment by djdd87** [comment]
Well the point of Docker is that it's hardware/OS independent, so I don't see why it won't work. Please attach screenshots of every tab of your SynoAI docker container.

**Comment by Neocramencer** [comment]
![Snag_73f28e](https://user-images.githubusercontent.com/9692854/141326146-0e7b63c2-67fb-4dbe-b668-a088c8748954.png)
![Snag_74876b](https://user-images.githubusercontent.com/9692854/141326236-8d1645e4-29ca-4d57-9a68-e04e9fa7978b.png)

Config will follow

**Comment by Neocramencer** [comment]
{
  "Logging": {
    "LogLevel": {
      "Default": "Warning",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Warning"
    }
  },

  "Url": "https://XXX:5001",
  "User": "admin",
  "Password": "XXX",

  "MinSizeX": 100,
  "MinSizeY": 100,
  
  "AI": {
    "Type": "DeepStack",
    "Url": "http://192.168.0.200:83"
  },

  "Notifiers": [
    {
      "Type": "Pushbullet",
      "ApiKey": "0.123456789"
    },
    {
      "Type": "Webhook",
      "Url": "http://server/images",
      "Method": "POST",
      "Field": "image"
    }
  ],

  "Cameras": [
    {
      "Name": "Kamera Garten",
      "Types": [ "Person", "Car" ],
      "Threshold": 45,
      "MinSizeX": 250,
      "MinSizeY": 500
    }
  ]
}

**Comment by Neocramencer** [comment]
removed the Password and the URL to my Synology.

**Comment by djdd87** [comment]
Did you stop and **reset** your container before you restarted? Because the docker image is showing as .Net 5.0.12 instead of .Net 5.0.2 which imples you didn't.

**Comment by djdd87** [comment]
What's your network tab showing? Bridge? Please provide screenshots of those sub tabs for network and volume too.

**Comment by Neocramencer** [comment]
![Snag_7a663a](https://user-images.githubusercontent.com/9692854/141327232-6804bef3-2ba3-4b56-9318-cb6a12c2a119.png)
![Snag_7b845c](https://user-images.githubusercontent.com/9692854/141327431-37392603-021d-46d5-bcec-e2cf2caa8ea1.png)

i removed the container before you published the new one and remvoed also the image. After your message i searched in the register tab again, downloaded the container and configured it according to the manual. I did no chaneed anythin to .net ENV.

**Comment by Neocramencer** [comment]
tested the development branch Image with the same result and error, also this image shows .net 5.0.12

**Comment by djdd87** [comment]
Sorry, not a clue then. It might be worth posting on the Synology or Docker reddit page or something and ask for some help.

**Comment by Neocramencer** [comment]
mhh ok found this:

https://stackoverflow.com/questions/66988943/could-not-execute-because-the-application-was-not-found-or-a-compatible-net-sdk

if i look in your dockerfile this could maybe the issue...  But iam not a developer...

**Comment by djdd87** [comment]
No I'm already using the correct SDK before building. In that question he's just using the runtime.

**Comment by Neocramencer** [comment]
You are sure? See screenshot, thats also the runtime, isnt it?
![Snag_988d48](https://user-images.githubusercontent.com/9692854/141332273-06a64c89-fbaa-42d6-a7f6-0de9d6ac389c.png)

**Comment by djdd87** [comment]
Yes for the base. See the 2nd one.

**Comment by Neocramencer** [comment]
ok so i will post this somewhere else but all other docker images running fine so something is wrong here.
when iam getting back a response i will repost here.

**Comment by Neocramencer** [comment]
thanks for your help so far

**Comment by djdd87** [comment]
I've got a few friends to remove and completely redo their installs. They are all working perfectly and their .net versions are showing as 5.0.2.

**Comment by djdd87** [comment]
Any update?

**Comment by Neocramencer** [comment]
found this:

https://stackoverflow.com/questions/69036186/docker-could-not-execute-because-the-application-was-not-found-or-a-compatible

I just want to tested this and forked your repo, can you give me a hint how to build your container? I habe installed docker for windows but need some cmdlets to compile the container.... :)

Thanks

**Comment by Neocramencer** [comment]
Just to be sure if you check your docker hub the .net version mentioned there is also 5.0.12:
![Snag_f5952eb](https://user-images.githubusercontent.com/9692854/141682263-5326d3da-4b3b-488f-8b85-3e2296b40884.png)

**Comment by Neocramencer** [comment]
And check the filesize of SynoAI.dll it is 0B...

**Comment by djdd87** [comment]
> found this:
> 
> https://stackoverflow.com/questions/69036186/docker-could-not-execute-because-the-application-was-not-found-or-a-compatible
> 
> I just want to tested this and forked your repo, can you give me a hint how to build your container? I habe installed docker for windows but need some cmdlets to compile the container.... :)
> 
> Thanks

Easiest way is to use Visual Studio Code. Open the project in that, install the docker extension. You will also need to install docker desktop. Then right click the dockerfile and click build and follow the wizard.

**Comment by djdd87** [comment]
> And check the filesize of SynoAI.dll it is 0B...

If you're referring to the line at the bottom of the image file, I'm pretty sure that's normal as it's just a command and not specifying the size of the DLL.

Let me know if you want me to build the image for you.

**Comment by thaindq** [comment]
> ![Snag_7a663a](https://user-images.githubusercontent.com/9692854/141327232-6804bef3-2ba3-4b56-9318-cb6a12c2a119.png) ![Snag_7b845c](https://user-images.githubusercontent.com/9692854/141327431-37392603-021d-46d5-bcec-e2cf2caa8ea1.png)
> 
> i removed the container before you published the new one and remvoed also the image. After your message i searched in the register tab again, downloaded the container and configured it according to the manual. I did no chaneed anythin to .net ENV.

Try to change `docker/sssAI/config -> /app` to `docker/sssAI/config/appsettings.json -> /app/appsettings.json`. I ran into the same issue and it turned out that I was mapping the whole `app` folder instead of just `appsettings.json` and `captures` folder

**Comment by djdd87** [comment]
That would definitely explain it! Don't know how I missed that myself.

**Comment by Neocramencer** [comment]
@thaindq THANK YOU very much, that did the trick. Sorry for replying late, i tried different things with the repo here with Visul Studio but that didnt worked so far.

Will now configure the Container and try it ;)
