### ISSUE TITLE
How to detect spider webs

### ISSUE THREAD

**Issue by JohannCR** [djdd87/SynoAI#60]
Hi,
These spiders are annoying... Apart from using insecticide, or spreading grease on the cameras (which I don't want to do), what other way is there to handle that ?

I was thinking of creating an automation to detect when the camera starts to record nearly continuously at night which would be a pretty accurate indicator (because spider webs glow under infra red light) except if there's lots of wind and the camera is too sensitive, but we could deactivate the automation when it happens in daylight...
Not sure if it'll work, but I'll take a shot and report back if anyone is interested. Any ideas to help ?
Thx

**Comment by djdd87** [comment]
Heh, funnily enough that annoys the hell out of me too. I can't remember the amount of times I've had to take a walk down the garden with a duster to stop my phone buzzing.

In regards to how to handle it... I guess you could set a max detection threshold per minute or similar, i.e. if the detection is triggered 5 times in a minute, then make it ignore all detectionr requests for X minutes.

**Comment by JohannCR** [comment]
Well if using direct notification on each movement I'm sure it must be annoying as hell... 

In my case I'm only notified when a person is detected, and it works pretty well even when there is a cobweb surprisingly. It fails only when the web moved before the person appeared, in the exact time window when surveillance station does not fire its rule again (I've put 60 seconds to avoid numerous notifications when someone stands in front of the cam). It does not happen often, but that's a security hole I'd like to control better ^^ then I'd clean the cameras as soon as the cobbweb appears and see if it's not too often to keep avoiding polluting solutions like bugspray and grease.

So I'm just looking for a way to reliably detect when surveillance station is excessively sollicited I guess. I'll ping HA each time there is a movment, independantly of what synoAI says and do some simple statistical analysis to see if it works.

**Comment by djdd87** [comment]
Unfortunately DeepStack often detects cobwebs as people for me, but I have the same issues when it doesn't, i.e. the web triggers a movement alert from SSS, but then it misses a person due to the throttling config. Let me know what you come up with.

**Comment by JohannCR** [comment]
I think I've had only one case of a cobweb detected as a person. Happens more often with my cats lol
For now I'll just count the rate of detections and see in a week or two if it's a reliable proxy.

For info here's my config :
In SSS action rule (the one that triggers synoAI) I added a webhook http://xx.xx.xx.xx:8123/api/webhook/move_camera_1 with POST or AUTO method (doesn't work wit GET)
In HA an automation 
trigger:
  - platform: webhook
    webhook_id: move_camera_1
which toggles a boolean.

**Comment by JohannCR** [comment]
I got nothing more than monitoring...
That's good enough for me, got a notification when it starts and I'll even add one when the rain removes it (happens sometimes too).
