### ISSUE TITLE
Email notifier sending from Destination, not Username

### ISSUE THREAD

**Issue by p-u-a** [djdd87/SynoAI#61]
I setup the email notifier to send through Outlook's SMTP server, let's use the example notifier settings below:

{
  "Type": "Email",
  "Destination": "youremail@example.com",
  "Host": "smtp.server.com",
  "Port": 465,
  "Username": "myoutlookaddress@outlook.com",
  "Password": "password",
  "Encryption": "Auto"
}

Outlook's server errored saying not authorised to send as "youremail@example.com". 

When changing Destination to match Username, it works fine. 

I look at the code in Email.cs and line 70 has:

email.From.Add(new MailboxAddress("SynoAI", **Destination**));

Should it be:

email.From.Add(new MailboxAddress("SynoAI", **Username**));

Great work on this too!  Coffees coming your way.

**Comment by djdd87** [comment]
I've updated the :latest build. There's now a "Sender" property (See the readme for more information). If that's left blank then it'll use Destination instead.

**Comment by p-u-a** [comment]
Works great now, thanks!

**Comment by djdd87** [comment]
No problem, thanks for the coffee :)
