### ISSUE TITLE
Support for Pushover notifications

### ISSUE THREAD

**Issue by p-u-a** [djdd87/SynoAI#62]
I'm no developer which unfortunately means I don't know how to properly build support for Pushover notifications. It's very similar to PushBullet and has all the API documentation at https://pushover.net - would it be at all possible to add support?

**Comment by djdd87** [comment]
Hey, it looks pretty easy. Leave it with me.

**Comment by p-u-a** [comment]
Awesome, thanks!

**Comment by Neocramencer** [comment]
That would really be cool ;)

**Comment by p-u-a** [comment]
Little more info if it helps or not, here's a Pushover notification I get when I use the SynoAI email notifier to send to my Pushover address -

![20220104_060134219_iOS](https://user-images.githubusercontent.com/87350987/148016540-6608b278-5f09-4d4b-802a-b22e79d5e2ea.png)

If the notifier just sent to Pushover what it's sending via email that'd be awesome, it has everything in it.  Hoping this one isn't a huge ask, I have more of a delay with the email sending/receiving than with DeepStack lol.  Sometimes Outlook doesn't like you sending too many emails at once so it drops the image too.

Again huge thanks for the work you've done, I couldn't go without it now.

**Comment by djdd87** [comment]
Yep, it'll work like this. I just need time to sit down and go through their API.

**Comment by p-u-a** [comment]
No worries, sorry don't want to come across demanding, just had a free chance to update a couple of things (kids, Christmas, New Years, back to work as I'm sure you can relate!).

**Comment by djdd87** [comment]
Now available on image `v1.1.0` or `latest`.
