### ISSUE TITLE
Everything = Nothing detected by the AI exceeding the defined confidence level and/or minimum size

### ISSUE THREAD

**Issue by mforrester1975** [djdd87/SynoAI#63]
New setup and trying to get this to function but on every event, the following line stops the notification going to push bullet.

Here is an example from the detection logs after changing to information
      GardenWiFi: car (52.9238300%) [Size: 188x69] [Start: 609,377 | End: 797,446]

I've removed all references to size so as per documentation this should default to 50x50

It would be good if the logs indicate where the detection rule is not being met, detection percentage or sizing

My appsettings file has the following setup
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft": "Warning",
      "Microsoft.Hosting.Lifetime": "Information"
    }
  },

  "Url": "XXXX:9901/",
  "User": "XXXXX",
  "Password": "XXXX",

  "AI": {
    "Type": "DeepStack",
    "Url": "http://XXXXXX:83"
  },

  "Notifiers": [
    {
      "Type": "Pushbullet",
      "ApiKey": "XXXXXX"
    }
  ],

  "Cameras": [
    {
      "Name": "GardenWiFi",
      "Types": [ "Person, Car" ],
      "Threshold": 50
    }
  ]
}
```

Container log file full output to show setup correctly
info: SynoAI.Startup[0]
      Processing config.
info: SynoAI.Startup[0]
      Processing camera config.
info: SynoAI.Startup[0]
      Processing notifier config.
info: SynoAI.Startup[0]
      Processing Pushbullet Config
info: SynoAI.Services.SynologyService[0]
      Initialising
info: SynoAI.Services.SynologyService[0]
      API: Querying end points
info: SynoAI.Services.SynologyService[0]
      API: Successfully mapped all end points
info: SynoAI.Services.SynologyService[0]
      Login: Authenticating
info: SynoAI.Services.SynologyService[0]
      Login: Successful
info: SynoAI.Services.SynologyService[0]
      GetCameras: Fetching Cameras
info: SynoAI.Services.SynologyService[0]
      GetCameras: Successful. Found 1 cameras.
info: SynoAI.Services.SynologyService[0]
      Initialisation successful.
info: Microsoft.Hosting.Lifetime[0]
      Now listening on: http://[::]:80
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Production
info: Microsoft.Hosting.Lifetime[0]
      Content root path: /app
info: SynoAI.Controllers.CameraController[0]
      GardenWiFi: Motion detected, fetching snapshot.
info: SynoAI.Services.SynologyService[0]
      GardenWiFi: Taking snapshot
info: SynoAI.Controllers.CameraController[0]
      GardenWiFi: Snapshot received (345ms).
info: SynoAI.Controllers.CameraController[0]
      GardenWiFi: Processing.
info: SynoAI.Services.AIService[0]
      GardenWiFi: DeepStackAI: Processed successfully (356ms).
info: SynoAI.Controllers.CameraController[0]
      GardenWiFi: car (75.3770400%) [Size: 180x75] [Start: 582,369 | End: 762,444]
info: SynoAI.Controllers.CameraController[0]
      GardenWiFi: Nothing detected by the AI exceeding the defined confidence level and/or minimum size
info: SynoAI.Controllers.CameraController[0]
      GardenWiFi: Finished (715ms).

**Comment by djdd87** [comment]
Hey, it's not matching, because you're looking for an object of  "Person, Car", which isn't a valid object. You need to separate them:

```"Types": [ "Person", "Car" ],
