### ISSUE TITLE
Error with Pushbullet - no space left

### ISSUE THREAD

**Issue by JohannCR** [djdd87/SynoAI#64]
Not receiving Pushbullet notifications anymore. Here is the error I get in docker :

error uploading file (invalid_request - File storage maximum exceeded. Delete uploaded files to clear storage space.)

Before hitting send on this issue, I checked in the pushbullet app and deleted my notification history. Lo and behold : it works again, so problem solved. I share it for those who would need it.

Anyone know how to avoid that in the future ?
Thx

**Comment by djdd87** [comment]
Just clear your notification history occasionally. This isn't really within the scope of SynoAI I'm afraid.

**Comment by JohannCR** [comment]
Sure, but that's a limitation of pushbullet (maybe you should mention it in the docs by the way). It's problematic because there is no way to know when that happens so one can miss some (a lot of ?) detections !
Is there at least a way to notify the user that this particular error occurs ? So that only one is missed instead of a bunch...

**Comment by djdd87** [comment]
Yeah actually you're right. It's probably just failing the upload of the file. So I could catch the upload failure and still send the detection message with an addendum stating that there was no storage space for the image.

**Comment by p-u-a** [comment]
I'd be onto pushbullet to add some way of auto deleting, would be better to fix it there than every potential app that uses pushbullet.

**Comment by djdd87** [comment]
The notifications will now send with an error message.
