### ISSUE TITLE
Telegram API Token

### ISSUE THREAD

**Issue by AKMedi9** [djdd87/SynoAI#68]
Im getting the following error when copying and pasting my telegram bot token from bot father:

System.ArgumentException: Invalid format. A valid token looks like "1234567:4TT8bAc8GHUspu3ERYn-KGcvsvGB9u_n4ddy". (Parameter 'token') 
at Telegram.Bot.TelegramBotClient..ctor(String token, HttpClient httpClient)
at SynoAI.Notifiers.Telegram.Telegram.SendAsync(Camera camera, ISnapshotManager snapshotManager, IEnumerable`1 foundTypes, ILogger logger) in /src/No...

I've tried two different bots and issued different Api tokens, all with the same result.

**Comment by djdd87** [comment]
Can you please provide your Telegram config?

**Comment by AKMedi9** [comment]
"Notifiers": [
    {
      "Type": "Telegram",
      "ChatID": "XXXXXXXXXX",
      "Token": "50566XXXXX:AAG-uKZxk5On24M7wnkvCGa1NNlWetXXXXX",
      "PhotoBaseURL": ""
    }
  ],

I obscured the data with X's.

**Comment by djdd87** [comment]
The config looks fine to me. Your token doesn't have any underscore ("_") anywhere in it though; every example I've ever seen does, but that could just be a coincidence.

I don't think this is an issue with SynoAI (seeing as I'm using it myself without any issues) so I suggest you try and get some support from Telegram.

**Comment by djdd87** [comment]
Closing - not a SynoAI issue.
