### ISSUE TITLE
Not getting types in webhook

### ISSUE THREAD

**Issue by thomasdg** [djdd87/SynoAI#71]
I read everywhere of other users getting the types of items found etc in the webhook. Also want to try to get those, as to filter out my static parked car as much as possible. Nothing appears in the webhook except of the image. If I try to do both image and types in a webhook push to home assistant, the push doesn't update the home assistant camera. Doing only image works fine, but of course doesn't show anything else.
I tried using webhook.site, but see no body...

This is my notification setup for the webhook.site trials:
```
    {
      "Type": "Webhook",
      "Cameras": [ "CameraGate" ],
      "Url": "https://webhook.site/db5d1de2-f29f-4863-98a9-xxxxxxxxxxxxx",
      "Method":"POST",
      "SendTypes": true,
      "SendImage": false
    }
```

I must be making some mistake or forget something, but what or where?

**Comment by thomasdg** [comment]
A small update/correction: if I tried requestcatcher.com, I did actually see the types, so it has to be something with that webhook.site website that doesn't behave correctly.

Homeassistant on the other hand stops updating the "motion webhook" once I add the "SendTypes":true statement to the appsettings.json config file. Anyone else having this issue?

This works fine:
`    {
      "Type": "Webhook",
      "Cameras": [ "CameraGate" ],
      "Url": "https://xxx.duckdns.org:8123/api/webhook/motion_gate",
      "Method":"POST",
      "SendImage": true
    },
`

This doesn't update anymore:
`    {
      "Type": "Webhook",
      "Cameras": [ "CameraGate" ],
      "Url": "https://xxx.duckdns.org:8123/api/webhook/motion_gate",
      "Method":"POST",
      "SendTypes": true,
      "SendImage": true
    },
`

**Comment by djdd87** [comment]
Do you have any error messages or status codes from the SynoAI logs?

What have you got set up on the HA side?

**Comment by djdd87** [comment]
Same issue as #8. Closing - please report findings there.
