### ISSUE TITLE
Docker container stops with Unhandled exception due to errors on DeepStack's end

### ISSUE THREAD

**Issue by JohannCR** [djdd87/SynoAI#72]
I'm starting to get these errors lately with docker stopping the container :

```
fail: SynoAI.Controllers.CameraController[0]
      Jardin: Failed to get get predictions.
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at SynoAI.Controllers.CameraController.GetAIPredications(Camera camera, Byte[] imageBytes) in /src/Controllers/CameraController.cs:line 367
   at SynoAI.Controllers.CameraController.Get(String id) in /src/Controllers/CameraController.cs:line 85
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by JohannCR** [comment]
Bit more info:
Running Docker 20.10.3-1239 on DSM 7.0.1-42218
Just in case it could be linked, I'm actually running a big hyperbackup job lasting nearly a day, so the NAS is a bit slower than usual, but nothing that kills any other container.

Here's my config : https://pastebin.com/KeC5u6DG

**Comment by p-u-a** [comment]
I'm getting this occasionally (rarely) too and it's when there's huge load on my NAS (918+). I also notice it says above this error something like internal server error when calling the deep stack api. When it happens again I'll try post my log file too.

**Comment by JohannCR** [comment]
Well it seems to go away when back to normal... I'll post if it happens again.
I don't know if it's a problem with deepstack or synoAI, but it would be worth it to fail gracefully and send a notification when it does ? Just not one for every crash though ^^

**Comment by djdd87** [comment]
Check out your logs, when this occurs it means that DeepStack did not return successful content. With debug enabled, look for something starting with  
> "DeepStackAI: Responded with"

The null reference exception shouldn't be happening though, it should be failing gracefully, but there's a missing return after it's detected the failure of DeepStack to return results.

**Comment by p-u-a** [comment]
This is what I get, but like i said hasn't happened and only happens with a high load on the NAS.  I'm going to change the motion detection method from Surveillance Station back to my cameras since i've noticed with 13 cameras it's running 30-40% CPU all the time just doing that.

warn: SynoAI.Services.AIService[0]
**Entrance: DeepStackAI: Failed to call API with HTTP status code 'InternalServerError'.**
fail: SynoAI.Controllers.CameraController[0]
Entrance: Failed to get get predictions.

**Comment by djdd87** [comment]
@p-u-a are you running with debug logging enabled? I'd like to see what response (if any) DeepStack gives when it's erroring so I can handle it better than just a totally useless HTTP status code 500 (InternalServerError).

Also I've fixed the unhandled exception and pushed a new :latest image to DockerHub.

**Comment by p-u-a** [comment]
I haven't had it error since then, so it hasn't happened after I turned debug logging on.  If it does it again I'll try capture the debug log.

**Comment by JohannCR** [comment]
I won't be able to try and generate an error message until a week or so, but I definitely will,
