### ISSUE TITLE
Recording Using Action Rule

### ISSUE THREAD

**Issue by robt7676** [djdd87/SynoAI#73]
Thank you for this updated version of AI recording for Synology.  Setting up the detection proved easy enough, but I can't for the life of me figure out how to send a webhook to Surveillance Station to record.  I tried putting "triggerUrl": "LINK FROM ACTION RULE" in the camera section of the appsettings file, but no dice.  Any thoughts?

**Comment by djdd87** [comment]
What are you trying to set up a webhook notification for?

**Comment by djdd87** [comment]
Provide your configuration file and I'll have a look.

**Comment by robt7676** [comment]
Thanks.  I tried the below and also tried putting the trigger line in the camera section.

{
  "Url": "http://192.168.1.13:5000",
  "User": "user",
  "Password": "password",

  "MinSizeX": 100,
  "MinSizeY": 100,
  
  "DaysToKeepCaptures": 14,
  
  "AI": {
    "Type": "DeepStack",
    "Url": "http://192.168.1.13:83"
  },

  "Notifiers": [
    {
      "Type": "Webhook",
      "Url": "http://192.168.1.13:5000/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method=\"Incoming\"&version=1&token=12345678901234567890",
      "Method": "POST",
      "Field": "image"
    }
  ],

  "Cameras": [
    {
      "Name": "Front",
      "Types": [ "Person" ],
      "Threshold": 60
    },
    {
      "Name": "Back",
      "Types": [ "Person" ],
      "Threshold": 60,
      "Exclusions": [
        {
            "Start": { "X": 1800, "Y": 400 },
            "End": { "X": 2350, "Y": 900 }
        },
        {
            "Start": { "X": 0, "Y": 0 },
            "End": { "X": 200, "Y": 500 }
        }
      ]
    }
  ]
}

**Comment by robt7676** [comment]
> Provide your configuration file and I'll have a look.

Thanks.  I tried the below and also tried putting the triggerurl line in the camera section.

{
  "Url": "http://192.168.1.13:5000",
  "User": "user",
  "Password": "password",

  "MinSizeX": 100,
  "MinSizeY": 100,
  
  "DaysToKeepCaptures": 14,
  
  "AI": {
    "Type": "DeepStack",
    "Url": "http://192.168.1.13:83"
  },

  "Notifiers": [
    {
      "Type": "Webhook",
      "Url": "http://192.168.1.13:5000/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method=\"Incoming\"&version=1&token=12345678901234567890",
      "Method": "POST",
      "Field": "image"
    }
  ],

  "Cameras": [
    {
      "Name": "Front",
      "Types": [ "Person" ],
      "Threshold": 60
    },
    {
      "Name": "Back",
      "Types": [ "Person" ],
      "Threshold": 60,
      "Exclusions": [
        {
            "Start": { "X": 1800, "Y": 400 },
            "End": { "X": 2350, "Y": 900 }
        },
        {
            "Start": { "X": 0, "Y": 0 },
            "End": { "X": 200, "Y": 500 }
        }
      ]
    }
  ]
}

**Comment by robt7676** [comment]
> Provide your configuration file and I'll have a look.

Thanks.  Here's what I was trying to use:

<html><head></head><body><div id="content"><div class="tabs "><nav class="tabs-navigation"><ul class="tabs-menu" role="tablist"><li class="tabs-menu-item json is-active" role="presentation"><span class="devtools-tab-line"></span></li></ul></nav></div></div><span class="devtools-tab-line"></span><span class="devtools-tab-line"></span><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"></div></div></div></div><div id="json-panel" style="visibility: visible; height: 100%;" class="tab-panel-box" role="tabpanel" aria-labelledby="json-tab"><div class="tab-panel json"><div class="jsonPanelBox tab-panel-inner"><div class="toolbar"><div class="devtools-separator"></div><input class="searchBox devtools-filterinput" placeholder="Filter JSON"></div><div class="panelContent">

  |  
-- | --
Url | "http://192.168.1.13:5000"
User | "user"
Password | "password"
MinSizeX | 100
MinSizeY | 100
DaysToKeepCaptures | 14
AI |  
Type | "DeepStack"
Url | "http://192.168.1.13:83"
Cameras |  
0 |  
Name | "Front"
Types |  
0 | "Person"
Threshold | 60
triggerUrl | "http://192.168.1.13:5000/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method=\"Incoming\"&version=1&token=123456789123456789123456789123456789"
1 |  
Name | "Back"
Types |  
0 | "Person"
Threshold | 60
2 |  
Name | "Driveway"
Types |  
0 | "Person"
Threshold | 60

</div></div></div></div></body></html>

**Comment by djdd87** [comment]
You need to define the notifiers - you haven't even defined that section - as [specified in the README](https://github.com/djdd87/SynoAI#example-appsettingsjson). There's loads of examples to reference there.

```json
 "Notifiers": [
    {
      "Type": "Webhook",
      "Url": "http://etc/etc"
    }
  ],
```

**Comment by djdd87** [comment]
> Hi. I don't see the original thread so apologies for creating a new one. I already tried creating a notifier section and adding the URL to it, but still wasn't picked up by the Action Rule; could be a typo somewhere so will try again. Also, with multiple cameras, it would require multiple URLs specific to each camera. Is there a way to specify a URL for each camera so the webhook only for the triggered camera is executed? Thanks again.

Please provide your example where you did it properly and I'll have a look.

**Comment by robt7676** [comment]
Appreciate the help.  I think I'm close and just need some way to specify the camera for each notifier, but admittedly not a programmer :(  In any case, here's the config:

{
  "Url": "http://192.168.1.13:5000",
  "User": "user",
  "Password": "password",

  "MinSizeX": 100,
  "MinSizeY": 100,
  
  "DaysToKeepCaptures": 14,
  
  "AI": {
    "Type": "DeepStack",
    "Url": "http://192.168.1.13:83"
  },

 "Notifiers": [
    {
      "Type": "Webhook",
      "Url": "http://192.168.1.13:5000/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method=\"Incoming\"&version=1&token=123456789123456789123456789123456789",
      "Method": "POST",
      "Field": "image"
    }
  ],

  "Cameras": [
    {
      "Name": "IPC-HFW1320S-Front",
      "Types": [ "Person", "Dog", "Cat" ],
      "Threshold": 60
    },
    {
      "Name": "IPC-HFW1320S-Back",
      "Types": [ "Person", "Dog", "Cat" ],
      "Threshold": 60
    },
    {
      "Name": "IPC-HFW1320S-Driveway",
      "Types": [ "Person", "Dog", "Cat" ],
      "Threshold": 60

    }
  ]
}

**Comment by djdd87** [comment]
Change:

``` json
    {
      "Type": "Webhook",
      "Url": "http://192.168.1.13:5000/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method=\"Incoming\"&version=1&token=123456789123456789123456789123456789",
      "Method": "POST",
      "Field": "image"
    }
```

To:

``` json
    {
      "Type": "Webhook",
      "Url": "http://192.168.1.13:5000/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method=\"Incoming\"&version=1&token=123456789123456789123456789123456789"
    }
```

**Comment by robt7676** [comment]
Thanks, I will try it.  And to specify the camera, do I just need to add  "Name": "Front" somewhere in there?

**Comment by djdd87** [comment]
Click the link I put previously for the example in the main Notifiers section of the README. 

Specify your cameras on the notification:

```json
{
  "Type": "Webhook",
  "Url": "http://192.168.1.13:5000/webapi/entry.cgi?api=SYNO.SurveillanceStation.Webhook&method=\"Incoming\"&version=1&token=123456789123456789123456789123456789",
   "Cameras": [ "Front"]
}
```

**Comment by robt7676** [comment]
Got it.  I will work on this, but suspect it'll work as intended now.  Thanks again!
