### ISSUE TITLE
Recording Webhook for Surveillance Station with Multiple Cameras

### ISSUE THREAD

**Issue by robt7676** [djdd87/SynoAI#74]
Hi.  I don't see the original thread so apologies for creating a new one.  I already tried creating a notifier section and adding the URL to it, but still wasn't picked up by the Action Rule; could be a typo somewhere so will try again.  Also, with multiple cameras, it would require multiple URLs specific to each camera.  Is there a way to specify a URL for each camera so the webhook only for the triggered camera is executed?  Thanks again.

**Comment by djdd87** [comment]
https://github.com/djdd87/SynoAI/issues/73
