### ISSUE TITLE
Feature request - custom, per-camera delay after movement detected and before retrieving snapshot

### ISSUE THREAD

**Issue by p-u-a** [djdd87/SynoAI#75]
Just been fiddling with the action rules and SynoAI delay and it got me thinking... One of my cameras looks at my side gate and when you open the gate from the outside, that triggers the action rule which triggers SynoAI.  However since that happens so quickly, the snapshot only has the gate opening, which correctly doesn't detect the person who's not yet walked through it.  It then doesn't trigger again for 5 seconds at least (depending on the interval and delay settings) and by that time the person is gone.

If we could delay the snapshot by a number of seconds, I could set it to say 3 seconds and by that time the gate will be open and the person will be walking through it.  The snapshot would capture that and then alert me.

**Comment by djdd87** [comment]
Now available in the :latest image.

``` json
{
  "Name": "SideGate",
  "Types": [ "Person" ],
  "Wait": 2500
}
```
