### ISSUE TITLE
Feature request - Delay after object detection, not after action rule trigger

### ISSUE THREAD

**Issue by p-u-a** [djdd87/SynoAI#76]
Another one I got thinking about.  I have some trees that are in view of the camera over my driveway.  Sometimes when the wind blows it triggers the motion action rule, triggering SynoAI.  It then delays for the duration you specify.  This is a great feature, but during this time there might be something I want to capture, but it's ignored as it's in the delay period.

If it could delay only after detecting the objects you're looking for, it could still be triggered by the trees then quickly triggered by an actual event and then delay.  You could also set the delay to something like 15 seconds in this case as if there's a delivery van arriving or something, you'd get one notification every 15 seconds, rather than one every default 5 (or miss it if you set the delay too high).

I know we're at the mercy of image processing time and also what surveillance stations considers a 'continuous event', but I still think it could be worthwhile.

**Comment by djdd87** [comment]
@p-u-a I'm not entirely sure what you're asking for. Are you requesting a delay after a successful object recognition that's different to the default? e.g.

- Tree blows, nothing detected
- Don't process again for 5
- Van arrives, person gets out, person detected
- Send alert
- Don't process again for 15

?

**Comment by p-u-a** [comment]
Yeah basically, I have it set so when movement is detected it analyses a snapshot every 2 seconds for about 8 seconds (so four snapshots are sent to DeepStack) and no delay set in SynoAI. 

Reason I did this was when something like my gate would open it would trigger the action rule, and there is no person to be detected. SynoAI would then ignore for the delay you set, but someone would walk through during the delay period and I'd miss it. 

Now it works great with multiple triggers and no delay set, but I get 3 notifications of a person (the first snapshot is just the moving gate, the other 3 is a person). 

If it could take a snapshot every 2 seconds for say 10 seconds, but delay as soon as a person or whatever is detected by DeepStack, it'd mean I'd only get the one notification. 

Analysis time is totally fast enough to deal with this, my DeepStack container spits out a result from a 2650x1440 image  in around 200-300ms so it's pretty quick. End to end trigger to notification is usually within a second. 

Does that make sense?

**Comment by p-u-a** [comment]
Basically:

> gate opens, nothing detected
> Triggered again by SS in 2 sec
> no one there yet, nothing detected
> Triggered again in 2 seconds by SS
> Someone's there, send alert
> Don't process again for 15
> Triggered again in 2 seconds by SS
> Ignore/delay
> and so on until 15 seconds is up or Ss stops triggering 

Basically just an "ignore if within X seconds of last notification time"

**Comment by djdd87** [comment]
Yep - so if you read #93 that I just logged, I think this'll cover your use-case.

**Comment by p-u-a** [comment]
100% it will! That's exactly what I'm after. Thanks heaps 😊

**Comment by djdd87** [comment]
Added in release ```latest``` or ```v1.1.2```.
