### ISSUE TITLE
Minor correction in the documentation for Home Assistant automation

### ISSUE THREAD

**Issue by digoben** [djdd87/SynoAI#79]
Minor, but important correction for Home Assistant automation. It seems the state of the push camera is "idle" and "recording" - without the quotation marks and starting with small letters. This caused me a bit of head scratching why the automation is not triggered. It works without state from/to, but then the automation is triggered twice - idle>recording and recording>idle.
For reference here is my automation:

alias: Detection test
description: ''
trigger:
  - platform: state
    entity_id: camera.taras_camera
    from: idle
    to: recording
condition: []
action:
  - service: notify.mobile_app_iphone_pawel
    data:
      message: Movement detected
mode: single

**Comment by djdd87** [comment]
Updated, is is now correct?

> Automations can be created using this webhook by checking for changes for the camera entity state. When the Push camera is not receiving any data, it will be in the state of idle. When the state switches to recording, it means that the webhook has started receiving data. For the fastest automation responses, perform your actions immediately on that state change.

**Comment by digoben** [comment]
Yes, thank you.

**Comment by mkammes** [comment]
Thanks, @digoben , I was scratching my head as well.

Question, though:

I'm assuming your defined entities above are of the camera itself. Doesn't this assume the camera is the device triggering the recording (e.g. move from idle to recording) and not Surveillance Station? Wouldn't the Synology camera entity be the device to poll to see if the Synology is recording or not?

In my use case, I don't record 24x7, and motion detection on my cameras is deactivated, and I use Surveillance Station to trigger recordings based on movement and then record the media to the Synology, not the camera.

Thanks!
