### ISSUE TITLE
Bug: Webhook is failing when sending to HA as their Push cannot support body content

### ISSUE THREAD

**Issue by djdd87** [djdd87/SynoAI#8]
Example error:
> Logger: homeassistant.components.webhook
> Source: components/push/camera.py:74
> Integration: Webhook (documentation, issues)
> First occurred: 8:21:27 (1 occurrences)
> Last logged: 8:21:27
> 
> Error processing webhook motion_driveway
> Traceback (most recent call last):
>   File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 96, in async_handle_webhook
>     response = await webhook["handler"](hass, webhook_id, request)
>   File "/usr/src/homeassistant/homeassistant/components/push/camera.py", line 74, in handle_webhook
>     data = dict(await request.post())
>   File "/usr/local/lib/python3.8/site-packages/aiohttp/web_request.py", line 649, in post
>     assert field.name is not None
> AssertionError

This does not occur when using a CURL command such as 
> curl -X POST -F "image=@%F" http://ha-server-ip:8123/api/webhook/motion_driveway

It looks as though the issue is due to the Webhook including both the image (with the correct field name "image") and body content. HA errors whenever body content is included as well as the image.

For the time being I'll just remove the body as there's no immediate requirement.

**Comment by eRJe79** [comment]
@djdd87 Do you see a chance to pick up this issue?

**Comment by djdd87** [comment]
Hey, I'll take a look when I next get chance.

**Comment by thomasdg** [comment]
After I got the other bugs squashed, I get the same error in home-assistant indeed, thanks @djdd87 for noticing :)

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/webhook/__init__.py", line 104, in async_handle_webhook
    response = await webhook["handler"](hass, webhook_id, request)
  File "/usr/src/homeassistant/homeassistant/components/webhook/trigger.py", line 30, in _handle_webhook
    result["data"] = await request.post()
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_request.py", line 698, in post
    assert field.name is not None
AssertionError
```

**Comment by thomasdg** [comment]
@gabrielpc1190 : Yes, then homeassistant gets the images but nothing else in the webhook. But as those are the default settings you can omit them and it will work. Just don't do the "SendTypes": true at the moment.

**Comment by djdd87** [comment]
@thomasdg @gabrielpc1190 , this should hopefully be fixed in the latest build. SendTypes has been removed as an option and you now only have the option of SendImage.

When SendImage is false, the data will be sent as application/json. 

When SendImage is true, the data will be sent as multipart/form-data in the correct format for that content type.
