### ISSUE TITLE
Pushover not working

### ISSUE THREAD

**Issue by Neocramencer** [djdd87/SynoAI#85]
Hi,

thanks for implementing Pushover API, unfortunatly it is not working., see screenshot of the log:

![image](https://user-images.githubusercontent.com/9692854/151127654-3f321d2a-7eb4-425b-b3e5-5916feb080b5.png)

Can you help?

Best regards
Marc

**Comment by djdd87** [comment]
Provide your pushover config please.

**Comment by Neocramencer** [comment]
![image](https://user-images.githubusercontent.com/9692854/151130623-7c8c3bd7-3827-45ae-bd02-ec8cc03c8f39.png)

Whole config attached.

**Comment by djdd87** [comment]
Can you try and specify sound and see if it fixes the issue? It should be optional, but it might be the cause as it's the only difference between yours and mine (which works)

"Type": "Pushover",
"ApiKey": "YOURKEY",
"UserKey": "YOURKEY",
"Sound": "siren"

**Comment by Neocramencer** [comment]
Will try this and come back. Need to trigger an event later.

**Comment by djdd87** [comment]
Just checked it quick, that is indeed the cause. Will push a fix in a minute.

**Comment by djdd87** [comment]
:V1.1.1 and :latest image have been published.
