### ISSUE TITLE
warn and failed errors

### ISSUE THREAD

**Issue by imzenreally** [djdd87/SynoAI#90]
so i set it all up and it appears to be talking to each other - but synoAI is erroring out when motion is detected

i get an error as follows:

`fail: SynoAI.Controllers.CameraController[0]
      Front Door: DeepStackAI: Failed to call API with HTTP status code 'Forbidden'
warn: SynoAI.Services.AIServices[0]
      Front Door: Failed to get get predictions.`

i have two cameras - Front Door and Driveway - ket the issues on both 

Deepstack log shows 
`[GIN] 2022/01/28 - 21:10..... | 403 |     2.07xxxxms | xxx.xxx.xxx.xxx | POST "/v1/vision/detection"`

**Comment by imzenreally** [comment]
sigh .... VISION-DETECTION: True --- apparently "True" is case senstive - i had 'true' testing to see if thats it now

**Comment by imzenreally** [comment]
now its "internal server error"

**Comment by djdd87** [comment]
Please provide the relevant log and and your config.

**Comment by imzenreally** [comment]
ok ... i found another 'typo' in a lower case letter

its working now - totally my fault - awesome piece of software - save me from having the fog trigger or headlamps trigger etc 

thanks man
