### ISSUE TITLE
Feature request: raw deepstack results in webhook

### ISSUE THREAD

**Issue by thomasdg** [djdd87/SynoAI#98]
First of all: thanks for getting the webhook to work with home assistant!

Last night I got it fixed in my setup but noticed a small problem... it was raining all the time and the SSS sent an image about every second to the SynoAI+DS. This of course always noted my car parked in the front. I would love to get the "raw" results of DS in the webhook, so I can see whether the car has actually moved more than a given threshold since the last analysed picture for that camera, or something like that. Would that be a possibility? Or does a workaround already exist?

**Comment by djdd87** [comment]
I can probably include the generic co ordinate and size information. I'd rather not expose the raw Deepstack data as I'd rather keep it generic for when I implement other AIs

**Comment by djdd87** [comment]
Example output:

``` json
{
  "camera": "Driveway",
  "foundTypes": [
    "Car"
  ],
  "predictions": [
    {
      "Label": "car",
      "Confidence": 38.89117,
      "MinX": 1738,
      "MinY": 420,
      "MaxX": 2304,
      "MaxY": 844,
      "SizeX": 566,
      "SizeY": 424
    }
  ],
  "message": "Motion detected on Driveway\n\nDetected 1 objects:\nCar"
}
```

**Comment by thomasdg** [comment]
@djdd87 Perfect solution, thanks again! Will try soon to get my automations use it.

**Comment by djdd87** [comment]
Added in `v1.2.0`
